### ISSUE TITLE
[Bug]: ValueError: 'ResizeMode.INNER_FIT' is not a valid ResizeMode occur when I use IpAdapter 

### ISSUE THREAD

**Issue by kris2per** [Panchovix/stable-diffusion-webui-reForge#103]
### Checklist

- [X] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Whenever I use Ipadapter I get the error: 'ResizeMode.INNER_FIT' is not a valid ResizeMode, disabling IpAdapter all together 

### Steps to reproduce the problem

1, Use Ipadapter
2. Get an error 

### What should have happened?

When u apply it, it should work w/o any errors. 

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-08-02-16-25.json](https://github.com/user-attachments/files/16472942/sysinfo-2024-08-02-16-25.json)

### Console logs

```Shell
Traceback (most recent call last):
  File "D:\ReForge\stable-diffusion-webui-reForge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\ReForge\stable-diffusion-webui-reForge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\ReForge\stable-diffusion-webui-reForge\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\ReForge\stable-diffusion-webui-reForge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ReForge\stable-diffusion-webui-reForge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\ReForge\stable-diffusion-webui-reForge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\ReForge\stable-diffusion-webui-reForge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\ReForge\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\lib_controlnet\controlnet_ui\controlnet_ui_group.py", line 616, in create_unit
    return ControlNetUnit.from_dict({
  File "D:\ReForge\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\lib_controlnet\external_code.py", line 309, in from_dict
    unit.resize_mode = resize_mode_from_value(unit.resize_mode)
  File "D:\ReForge\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\lib_controlnet\external_code.py", line 59, in resize_mode_from_value
    return ResizeMode(resize_mode_aliases.get(value, value))
  File "C:\Users\Kris\AppData\Local\Programs\Python\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\Kris\AppData\Local\Programs\Python\Python310\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'ResizeMode.INNER_FIT' is not a valid ResizeMode
```

**Comment by kris2per** [comment]
> Hi there, thanks for the report. Did a new commit that should take care of this, can you check if it works fine?
> 
> [e4931f7](https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/e4931f7f5a9b6d4223316b3dfce46d44219d734b)
Still has another set of errors 

Moving model(s) has taken 0.72 seconds
*** Error running process_before_every_sampling: D:\ReForge\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\ReForge\stable-diffusion-webui-reForge\modules\scripts.py", line 891, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\ReForge\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\ReForge\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 580, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
      File "D:\ReForge\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\ReForge\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 524, in process_unit_before_every_sampling
        params.model.process_before_every_sampling(p, cond, mask, *args, **kwargs)
      File "D:\ReForge\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_ipadapter\scripts\forge_ipadapter.py", line 153, in process_before_every_sampling
        unet = opIPAdapterApply(
    TypeError: IPAdapterApply.apply_ipadapter() got an unexpected keyword argument 'image_embeds'

**Comment by Panchovix** [comment]
Hi there, sorry for the delay.

Does the error still happens? Does it happen on dev_upstream as well?

Can you explain me how to reproduce the issue? I'm not sure how to use IP-Adapter.
