### ISSUE TITLE
[Bug]: Inpainting ControlNet models no longer working

### ISSUE THREAD

**Issue by altoiddealer** [Panchovix/stable-diffusion-webui-reForge#110]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

I'm currently using the Main branch - I am on current version.

This is a new issue, separate from my previous one https://github.com/Panchovix/stable-diffusion-webui-reForge/issues/84

That one was closed as completed, but it was no actually resolved and that issue is now applicable to the main branch.

Furthermore!  No inpainting models are working correctly now on the main branch.

Tested in both txt2img and img2img, using preprocessors `inpaint_only`, `inpaint_only+lama`, and `inpaint_global_harmonious`:

- controlnetxlCNXL_ecomxlInpaint [ad895a99]
- Kataragi_inpaintXL-fp16 [ad3c2578]
- controlnetxlCNXL_destitechInpaintv2 [e799aa20] (only tried preprocessor: `None`)

These inpainting models work on the current upstream ControlNet extension, and "old Forge", and were also working on your main branch a few days ago - now, none working.

Aside from **destitechInpaintv2** which required preprocessor None (now `main` has same issue I reported for `dev_upstream`), the other models are having no effect at all on generation, and the generated result is just being stuffed into the mask.  No ControlNet guidance is being applied.

### Steps to reproduce the problem

Use an inpainting ControlNet model.
No guidance is applied

### What should have happened?

inpainting guidance is applied.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-08-06-13-38.json](https://github.com/user-attachments/files/16511111/sysinfo-2024-08-06-13-38.json)

### Console logs

```Shell
venv "D:\0_AI\stable-diffusion-webui-reForge\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f1.0.1-v1.10.1RC-previous-394-g2cb35c91
Commit hash: 2cb35c9111a96fc459b1724e487c3ae072f26773
CUDA 12.1
Launching Web UI with arguments: --disable-xformers --ckpt-dir 'D:\0_AI\stable-diffusion-webui-reforge\xtra\models' --lora-dir 'D:\0_AI\stable-diffusion-webui-reforge\xtra\Lora' --embeddings-dir 'D:\0_AI\stable-diffusion-webui-reforge\xtra\embeddings' --ui-settings-file 'D:\0_AI\stable-diffusion-webui-reforge\config-xtra.json' --cuda-stream --pin-shared-memory --cuda-malloc --api --listen --api-server-stop
Using cudaMallocAsync backend.
Total VRAM 12282 MB, total RAM 32536 MB
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
CUDA Stream Activated:  True
Using pytorch cross attention
ControlNet preprocessor location: D:\0_AI\stable-diffusion-webui-reForge\extensions-builtin\forge_legacy_preprocessors\annotator\downloads
[-] ADetailer initialized. version: 24.8.0, num models: 10
WARNING:dinov2:xFormers not available
WARNING:dinov2:xFormers not available
09:22:55 - ReActor - STATUS - Running v0.7.1-a1 on Device: CUDA
Loading model PonyXL\realcartoonPony_v1.safetensors [2295809170] (1 of 1)
Loading weights [2295809170] from D:\0_AI\stable-diffusion-webui-reforge\xtra\models\PonyXL\realcartoonPony_v1.safetensors
2024-08-06 09:22:56,575 - ControlNet - INFO - ControlNet UI callback registered.
model_type EPS
UNet ADM Dimension 2816
Running on local URL:  http://0.0.0.0:7860
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE

To create a public link, set `share=True` in `launch()`.
Startup time: 27.6s (prepare environment: 10.4s, import torch: 2.7s, import gradio: 1.7s, setup paths: 1.6s, initialize shared: 0.1s, other imports: 1.1s, list SD models: 0.8s, load scripts: 3.5s, create ui: 0.9s, gradio launch: 4.2s, add APIs: 0.7s).
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection'}
Loading VAE weights specified in settings: D:\0_AI\stable-diffusion-webui-reForge\models\VAE\sdxl_vae.safetensors
To load target model SDXLClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  11025.633880615234
[Memory Management] Model Memory (MB) =  2144.3546981811523
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  7857.279182434082
Moving model(s) has taken 0.31 seconds
Model PonyXL\realcartoonPony_v1.safetensors [2295809170] loaded in 7.4s (load weights from disk: 0.5s, forge load real models: 5.9s, load VAE: 0.2s, load textual inversion embeddings: 0.2s, calculate empty prompt: 0.6s).
2024-08-06 09:24:29,550 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-08-06 09:24:29,558 - ControlNet - INFO - Using preprocessor: None
2024-08-06 09:24:29,558 - ControlNet - INFO - preprocessor resolution = 1024
[] []
2024-08-06 09:24:30,729 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\0_AI\stable-diffusion-webui-reForge\models\ControlNet\sdxl\controlnetxlCNXL_destitechInpaintv2.safetensors
2024-08-06 09:24:30,730 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-08-06 09:24:30,735 - ControlNet - INFO - Using preprocessor: inpaint_only
2024-08-06 09:24:30,735 - ControlNet - INFO - preprocessor resolution = 1024
[] []
2024-08-06 09:24:31,847 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\0_AI\stable-diffusion-webui-reForge\models\ControlNet\NEW\Kataragi_inpaintXL-fp16.safetensors
2024-08-06 09:24:31,848 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-08-06 09:24:31,852 - ControlNet - INFO - Using preprocessor: None
2024-08-06 09:24:31,853 - ControlNet - INFO - preprocessor resolution = 1024
[] []
2024-08-06 09:24:32,946 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\0_AI\stable-diffusion-webui-reForge\models\ControlNet\NEW\xinsir_controlnet-depth-sdxl-1.0.safetensors
2024-08-06 09:24:33,444 - ControlNet - INFO - ControlNet Method None patched.
To load target model AutoencoderKL
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  9191.955797195435
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  8008.3987159729
Moving model(s) has taken 0.04 seconds
2024-08-06 09:24:34,015 - ControlNet - INFO - ControlNet Method inpaint_only patched.
2024-08-06 09:24:34,021 - ControlNet - INFO - ControlNet Method None patched.
To load target model SDXL
To load target model ControlNet
To load target model ControlNet
To load target model ControlNet
Begin to load 4 models
[Memory Management] Current Free GPU Memory (MB) =  10934.3104763031
[Memory Management] Model Memory (MB) =  4897.086494445801
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  5013.2239818573
[Memory Management] Current Free GPU Memory (MB) =  6037.2142162323
[Memory Management] Model Memory (MB) =  2386.120147705078
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  2627.0940685272217
[Memory Management] Current Free GPU Memory (MB) =  3651.0940685272217
[Memory Management] Model Memory (MB) =  2386.120147705078
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  240.97392082214355
[Memory Management] Current Free GPU Memory (MB) =  610.5168895721436
[Memory Management] Model Memory (MB) =  2386.120147705078
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  -2799.6032581329346
[Memory Management] Requested ASYNC Preserved Memory (MB) =  0.0
[Memory Management] Parameters Loaded to ASYNC Stream (MB) =  2386.120147705078
[Memory Management] Parameters Loaded to GPU (MB) =  0.0
Moving model(s) has taken 3.16 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:25<00:00,  1.96it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████| 50/50 [00:24<00:00,  2.00it/s]
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  6154.834829330444
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  4971.27774810791
Moving model(s) has taken 2.09 seconds
Total progress: 100%|██████████████████████████████████████████████████████████████████| 50/50 [00:28<00:00,  1.77it/s]
2024-08-06 09:25:44,560 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE██| 50/50 [00:28<00:00,  2.00it/s]
2024-08-06 09:25:44,564 - ControlNet - INFO - Using preprocessor: inpaint_only
2024-08-06 09:25:44,564 - ControlNet - INFO - preprocessor resolution = 1024
2024-08-06 09:25:44,584 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\0_AI\stable-diffusion-webui-reForge\models\ControlNet\NEW\Kataragi_inpaintXL-fp16.safetensors
2024-08-06 09:25:44,585 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-08-06 09:25:44,589 - ControlNet - INFO - Using preprocessor: None
2024-08-06 09:25:44,589 - ControlNet - INFO - preprocessor resolution = 1024
2024-08-06 09:25:44,608 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\0_AI\stable-diffusion-webui-reForge\models\ControlNet\NEW\xinsir_controlnet-depth-sdxl-1.0.safetensors
2024-08-06 09:25:44,805 - ControlNet - INFO - ControlNet Method inpaint_only patched.
2024-08-06 09:25:44,811 - ControlNet - INFO - ControlNet Method None patched.
To load target model SDXL
To load target model ControlNet
To load target model ControlNet
Begin to load 3 models
Reuse 1 loaded models
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  8540.947328567505
[Memory Management] Model Memory (MB) =  4897.086494445801
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  2619.860834121704
[Memory Management] Current Free GPU Memory (MB) =  3643.851068496704
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  2619.851068496704
[Memory Management] Current Free GPU Memory (MB) =  3643.851068496704
[Memory Management] Model Memory (MB) =  2386.120147705078
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  233.73092079162598
Moving model(s) has taken 1.34 seconds
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:24<00:00,  2.06it/s]
To load target model AutoencoderKL████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:23<00:00,  2.04it/s]
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  6142.577180862427
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  4959.020099639893
Moving model(s) has taken 0.71 seconds
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:25<00:00,  1.96it/s]
2024-08-06 09:29:41,227 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE█████████████████████████████████████| 50/50 [00:25<00:00,  2.04it/s]
2024-08-06 09:29:41,232 - ControlNet - INFO - Using preprocessor: None
2024-08-06 09:29:41,232 - ControlNet - INFO - preprocessor resolution = 1024
2024-08-06 09:29:41,251 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\0_AI\stable-diffusion-webui-reForge\models\ControlNet\NEW\Kataragi_inpaintXL-fp16.safetensors
2024-08-06 09:29:41,252 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-08-06 09:29:41,256 - ControlNet - INFO - Using preprocessor: None
2024-08-06 09:29:41,256 - ControlNet - INFO - preprocessor resolution = 1024
2024-08-06 09:29:41,274 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\0_AI\stable-diffusion-webui-reForge\models\ControlNet\NEW\xinsir_controlnet-depth-sdxl-1.0.safetensors
2024-08-06 09:29:41,281 - ControlNet - INFO - ControlNet Method None patched.
2024-08-06 09:29:41,288 - ControlNet - INFO - ControlNet Method None patched.
To load target model SDXL
To load target model ControlNet
To load target model ControlNet
Begin to load 3 models
Reuse 1 loaded models
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  6142.569532394409
[Memory Management] Model Memory (MB) =  4897.086494445801
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  221.4830379486084
[Memory Management] Current Free GPU Memory (MB) =  566.2935848236084
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  -457.7064151763916
[Memory Management] Requested ASYNC Preserved Memory (MB) =  0.0
[Memory Management] Parameters Loaded to ASYNC Stream (MB) =  2386.120147705078
[Memory Management] Parameters Loaded to GPU (MB) =  0.0
[Memory Management] Current Free GPU Memory (MB) =  2952.4137325286865
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  1928.4137325286865
Moving model(s) has taken 1.15 seconds
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:23<00:00,  2.09it/s]
To load target model AutoencoderKL████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:23<00:00,  2.06it/s]
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  8516.439680099487
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  7332.882598876953
Moving model(s) has taken 0.69 seconds
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:25<00:00,  1.99it/s]
2024-08-06 09:30:27,465 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE█████████████████████████████████████| 50/50 [00:25<00:00,  2.06it/s]
2024-08-06 09:30:27,469 - ControlNet - INFO - Using preprocessor: inpaint_only
2024-08-06 09:30:27,469 - ControlNet - INFO - preprocessor resolution = 1024
[] []
2024-08-06 09:30:28,603 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\0_AI\stable-diffusion-webui-reForge\models\ControlNet\NEW\controlnetxlCNXL_ecomxlInpaint.safetensors
2024-08-06 09:30:28,604 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-08-06 09:30:28,609 - ControlNet - INFO - Using preprocessor: None
2024-08-06 09:30:28,609 - ControlNet - INFO - preprocessor resolution = 1024
2024-08-06 09:30:28,630 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\0_AI\stable-diffusion-webui-reForge\models\ControlNet\NEW\xinsir_controlnet-depth-sdxl-1.0.safetensors
2024-08-06 09:30:28,816 - ControlNet - INFO - ControlNet Method inpaint_only patched.
2024-08-06 09:30:28,822 - ControlNet - INFO - ControlNet Method None patched.
To load target model SDXL
To load target model ControlNet
To load target model ControlNet
Begin to load 3 models
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  8516.43203163147
[Memory Management] Model Memory (MB) =  4897.086494445801
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  2595.345537185669
[Memory Management] Current Free GPU Memory (MB) =  3619.335771560669
[Memory Management] Model Memory (MB) =  2386.120147705078
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  209.21562385559082
[Memory Management] Current Free GPU Memory (MB) =  571.9109363555908
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  -452.0890636444092
[Memory Management] Requested ASYNC Preserved Memory (MB) =  0.0
[Memory Management] Parameters Loaded to ASYNC Stream (MB) =  2386.120147705078
[Memory Management] Parameters Loaded to GPU (MB) =  0.0
Moving model(s) has taken 2.65 seconds
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:23<00:00,  2.09it/s]
To load target model AutoencoderKL████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:23<00:00,  2.05it/s]
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  8504.18203163147
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  7320.624950408936
Moving model(s) has taken 1.20 seconds
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:25<00:00,  1.94it/s]
2024-08-06 09:32:07,108 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE█████████████████████████████████████| 50/50 [00:25<00:00,  2.05it/s]
2024-08-06 09:32:07,113 - ControlNet - INFO - Using preprocessor: inpaint_only
2024-08-06 09:32:07,113 - ControlNet - INFO - preprocessor resolution = 1024
2024-08-06 09:32:07,133 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\0_AI\stable-diffusion-webui-reForge\models\ControlNet\NEW\controlnetxlCNXL_ecomxlInpaint.safetensors
To load target model SDXLClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  8344.742311477661
[Memory Management] Model Memory (MB) =  2144.3546981811523
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  5176.387613296509
Moving model(s) has taken 0.28 seconds
2024-08-06 09:32:08,244 - ControlNet - INFO - ControlNet Method inpaint_only patched.
To load target model SDXL
To load target model ControlNet
Begin to load 2 models
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  8318.253053665161
[Memory Management] Model Memory (MB) =  4897.086494445801
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  2397.1665592193604
[Memory Management] Current Free GPU Memory (MB) =  3421.1567935943604
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  2397.1567935943604
Moving model(s) has taken 1.22 seconds
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:07<00:00,  2.15it/s]
Memory cleanup has taken 0.67 seconds█████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:07<00:00,  2.09it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:08<00:00,  1.83it/s]
2024-08-06 09:33:28,274 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE█████████████████████████████████████| 16/16 [00:08<00:00,  2.09it/s]
2024-08-06 09:33:28,278 - ControlNet - INFO - Using preprocessor: inpaint_only+lama
2024-08-06 09:33:28,278 - ControlNet - INFO - preprocessor resolution = 1024
To load target model FFCResNetGenerator
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  8342.767702102661
[Memory Management] Model Memory (MB) =  194.76826095581055
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  7123.999441146851
Moving model(s) has taken 0.19 seconds
2024-08-06 09:33:29,385 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\0_AI\stable-diffusion-webui-reForge\models\ControlNet\NEW\controlnetxlCNXL_ecomxlInpaint.safetensors
2024-08-06 09:33:29,756 - ControlNet - INFO - ControlNet Method inpaint_only+lama patched.
To load target model SDXL
To load target model ControlNet
Begin to load 2 models
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  8139.616802215576
[Memory Management] Model Memory (MB) =  4897.086494445801
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  2218.5303077697754
[Memory Management] Current Free GPU Memory (MB) =  2179.7510108947754
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  1155.7510108947754
Moving model(s) has taken 0.58 seconds
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:07<00:00,  2.14it/s]
Memory cleanup has taken 0.73 seconds█████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:07<00:00,  2.10it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:09<00:00,  1.77it/s]
2024-08-06 09:34:15,906 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE█████████████████████████████████████| 16/16 [00:09<00:00,  2.10it/s]
2024-08-06 09:34:15,913 - ControlNet - INFO - Using preprocessor: inpaint_global_harmonious
2024-08-06 09:34:15,913 - ControlNet - INFO - preprocessor resolution = 1024
2024-08-06 09:34:15,938 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\0_AI\stable-diffusion-webui-reForge\models\ControlNet\NEW\controlnetxlCNXL_ecomxlInpaint.safetensors
2024-08-06 09:34:16,442 - ControlNet - INFO - ControlNet Method inpaint_global_harmonious patched.
To load target model SDXL
To load target model ControlNet
Begin to load 2 models
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  8333.502424240112
[Memory Management] Model Memory (MB) =  4897.086494445801
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  2412.4159297943115
[Memory Management] Current Free GPU Memory (MB) =  3436.4061641693115
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  2412.4061641693115
Moving model(s) has taken 1.00 seconds
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:07<00:00,  2.09it/s]
Memory cleanup has taken 0.90 seconds█████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:07<00:00,  2.04it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:09<00:00,  1.71it/s]
2024-08-06 09:34:36,878 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE█████████████████████████████████████| 16/16 [00:09<00:00,  2.04it/s]
2024-08-06 09:34:36,884 - ControlNet - INFO - Using preprocessor: inpaint_global_harmonious
2024-08-06 09:34:36,884 - ControlNet - INFO - preprocessor resolution = 1024
2024-08-06 09:34:36,910 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\0_AI\stable-diffusion-webui-reForge\models\ControlNet\NEW\Kataragi_inpaintXL-fp16.safetensors
2024-08-06 09:34:37,423 - ControlNet - INFO - ControlNet Method inpaint_global_harmonious patched.
To load target model SDXL
To load target model ControlNet
Begin to load 2 models
[Memory Management] Current Free GPU Memory (MB) =  10866.54701423645
[Memory Management] Model Memory (MB) =  4897.086494445801
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  4945.460519790649
[Memory Management] Current Free GPU Memory (MB) =  5969.450754165649
[Memory Management] Model Memory (MB) =  2386.120147705078
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  2559.3306064605713
Moving model(s) has taken 2.24 seconds
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:07<00:00,  2.08it/s]
To load target model AutoencoderKL████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:07<00:00,  2.02it/s]
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  8467.926866531372
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  7284.369785308838
Moving model(s) has taken 0.95 seconds
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:09<00:00,  1.70it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:09<00:00,  2.02it/s]
```

**Comment by Panchovix** [comment]
Understood. Reverted the controlnet change for now.

I will probably only add the new/missing preprocessors, instead of modifying the existing ones.

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/a7989af8412d67f59cd294d76df980aeb6559064

**Comment by Panchovix** [comment]
Okay I have also now added only new preprocessors, instead of editing the existing ones

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/ee2b78b07f19075dab5c68690685d7cb62c5f52d

I closed the other issue because I couldn't replicate sadly (but it can be because I'm bad at this). You can re open if you want.

Can you let me know now if inpaint works as it should on main?

**Comment by altoiddealer** [comment]
It's still behaving the same way

To illustrate what is happening...

During generation:
![Screenshot 2024-08-06 122507](https://github.com/user-attachments/assets/ed90b856-a287-461c-b92b-b4b56495cf0c)

Result:
![Screenshot 2024-08-06 122517](https://github.com/user-attachments/assets/1ea9a110-c102-4f48-b834-0ed479b91834)

**Comment by altoiddealer** [comment]
When things are working normally and correctly, the original image is in the preview window and you only see the masked area getting updated.

Please note that the Inpainting models behave differently from most of the other ControlNet types, in that they are directly driven by the "Mask".  It seems like the mask has no effect at all until the generation completes

**Comment by Panchovix** [comment]
Are you using inpaint_only for this? the inpaint_only_variant is like the controlnet upstream one, which could give issues, while the one that doesn't have this should be the OG one.

![imagen](https://github.com/user-attachments/assets/1e33f47a-ce2b-4cf0-b627-5f31e514ac88)

I think I haven't do any major change besides that on main branch. 

The other is the modification of processing.py

This commit is just before that https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/e99cd06312a58c4b35f1575d8070fab2bf033439

You can get to latest commit on main, and then do

"git revert 651c7b2 1b1ab94 89f1180"

If you want to test on latest commit without processing modifications. To return to "stock" state, git stash should work.

**Comment by altoiddealer** [comment]
I used the git revert

![Screenshot 2024-08-06 124033](https://github.com/user-attachments/assets/8aa19fe2-c81f-4fa7-a030-e1215612bcbf)

I don't have as many preprocessor options as you've shown - only these:

![Screenshot 2024-08-06 124219](https://github.com/user-attachments/assets/9aac1e28-5370-459e-971d-37b701c4bc2c)


It's still the same issue again, where the mask is seemingly completely ignored until the final step.

Note that this around after using git revert I had this error on startup

```
Using pytorch cross attention
*** Error loading script: legacy_preprocessors.py
    Traceback (most recent call last):
      File "D:\0_AI\stable-diffusion-webui-reForge\modules\scripts.py", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\0_AI\stable-diffusion-webui-reForge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\0_AI\stable-diffusion-webui-reForge\extensions-builtin\forge_legacy_preprocessors\scripts\legacy_preprocessors.py", line 17, in <module>
        from legacy_preprocessors.preprocessor_compiled import legacy_preprocessors
      File "D:\0_AI\stable-diffusion-webui-reForge\extensions-builtin\forge_legacy_preprocessors\legacy_preprocessors\preprocessor_compiled.py", line 1, in <module>
        from legacy_preprocessors.preprocessor import *
      File "D:\0_AI\stable-diffusion-webui-reForge\extensions-builtin\forge_legacy_preprocessors\legacy_preprocessors\preprocessor.py", line 16, in <module>
        from scripts.logging import logger
    ModuleNotFoundError: No module named 'scripts.logging'
    ```

**Comment by Panchovix** [comment]
I see, you can ignore the scripts.logging error (the variants depends from this file)

Use git stash to get it as default state.

Now, the latest commit because either processing or controlnet changes is e53cf13

So, can you test with `git checkout e53cf13` and see if the issue persists?

**Comment by altoiddealer** [comment]
I did `git checkout` back to this commit (when I first started reporting problems) and everything works fine here.

What I'm going to do now is just walk back from the latest and greatest version using git checkout until I find the problematic one.

Stand by...

**Comment by altoiddealer** [comment]
This is the commit where the issue begins
https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/284d07dbfcb6742aa30658a0ef7ada796e74aefa

I'm going to do you a favor and see if I can debug this a bit more myself.  Will report back shortly.

**Comment by altoiddealer** [comment]
The issue seems to be in `sd_samplers_cfg_denoiser.py` ... seeing if I can debug a bit further for you

**Comment by Panchovix** [comment]
Hmm interesting, that change was adding a different way to do CFG Denoisers. I think, I should remove the A1111 since it gives a lot of issues.

Now, either reForge or reForgedev CFG Denoiser should work fine. But, if with either doesn't work, I can try to restore the stock reForge CFG Denoiser only and see how it goes.

**Comment by altoiddealer** [comment]
Ahh yes indeed, the Reforge CFG Denoiser setting is fixing it.

I'm going to try that on current main as well...

**Comment by altoiddealer** [comment]
Well alright!  That does seem to resolve everything.

Even the destitech inpainting model with preprocessor 'None'.

I'm not sure if the CFG Denoiser label `A1111` is really an accurate label, though, being that this problem does not happen on A1111... and assuming this problem is directly stemming from "CFG Denoising".

**Comment by altoiddealer** [comment]
It's broken on `dev_upstream` (tried: reForge CFG).  I had tried all CFG Denoiser settings with my last Issue report, but none worked then either..

**Comment by Panchovix** [comment]
Understood. I though that was fixed after a commit I did some days ago. But at least, main is working as it should. Will reopen the other issue for now.
