### ISSUE TITLE
[Bug]: fp8 makes model loading fail with Promotion for Float8 types is not supported

### ISSUE THREAD

**Issue by Vektor8298** [Panchovix/stable-diffusion-webui-reForge#118]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When trying to run sd-webui-reforge with fp8, it fails to load the model and never runs, throwing an error.

### Steps to reproduce the problem

1. Enable fp8 with `--unet-in-fp8-e5m2` or `--unet-in-fp8-e4m3fn` in webui-user.sh
2. Run webui.sh
3. Observe the error when loading the SD Model

### What should have happened?

It should load the model and let me run the webui.

### Sysinfo

[sysinfo-2024-08-10-14-04.json](https://github.com/user-attachments/files/16569801/sysinfo-2024-08-10-14-04.json)

### Console logs

```Shell
################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
################################################################

################################################################
Running on voivod user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
glibc version is 2.40
Check TCMalloc: libtcmalloc_minimal.so.4
libtcmalloc_minimal.so.4 is linked with libc.so,execute LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so.4
Python 3.10.6 (main, May  5 2024, 11:48:59) [GCC 13.2.1 20240417]
Version: f1.0.1-v1.10.1RC-latest-677-g6c01cab4
Commit hash: 6c01cab47e6a151ee595334e960016aea87f2d4e
Installing requirements
loading WD14-tagger reqs from /home/voivod/stable-diffusion-webui-forge/extensions/stable-diffusion-webui-wd14-tagger/requirements.txt
Checking WD14-tagger requirements.
Launching Web UI with arguments: --device-id=0 --disable-xformers --attention-pytorch --cuda-malloc --cuda-stream --unet-in-fp8-e4m3fn --enable-insecure-extension-access --no-gradio-queue --listen --port 7861
Using cudaMallocAsync backend.
Total VRAM 3806 MB, total RAM 15717 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --always-normal-vram
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : cudaMallocAsync
Hint: your device supports --pin-shared-memory for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  True
2024-08-10 11:00:21.835997: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-08-10 11:00:21.949190: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-10 11:00:22.011715: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-10 11:00:22.022164: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-10 11:00:22.108505: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-10 11:00:23.062633: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Using pytorch cross attention
ControlNet preprocessor location: /home/voivod/stable-diffusion-webui-forge/models/ControlNetPreprocessor
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.6.0, num models: 15
== WD14 tagger /gpu:0, uname_result(system='Linux', node='terminalredux', release='6.9.9-arch1-1.2-g14', version='#1 SMP PREEMPT_DYNAMIC Tue, 16 Jul 2024 05:59:42 +0000', machine='x86_64') ==
Loading model SDXL/4thTailAnimeHentai_v045.safetensors [45a5febab2] (1 of 1)
Loading weights [45a5febab2] from /home/voivod/stable-diffusion-webui-forge/models/Stable-diffusion/SDXL/4thTailAnimeHentai_v045.safetensors
2024-08-10 11:00:30,557 - ControlNet - INFO - ControlNet UI callback registered.
/home/voivod/stable-diffusion-webui-forge/modules/gradio_extensons.py:25: GradioDeprecationWarning: `height` is deprecated in `Interface()`, please use it within `launch()` instead.
  res = original_IOComponent_init(self, *args, **kwargs)
Scanning <DirEntry 'deepdanbooru-v3-20211112-sgd-e28'> as deepdanbooru project
Scanning <DirEntry 'deepdanbooru-v4-20200814-sgd-e30'> as deepdanbooru project
Running on local URL:  http://0.0.0.0:7861

To create a public link, set `share=True` in `launch()`.
IIB Database file has been successfully backed up to the backup folder.
Startup time: 22.4s (prepare environment: 9.3s, import torch: 2.6s, import gradio: 0.7s, setup paths: 3.7s, other imports: 0.5s, load scripts: 4.5s, create ui: 0.6s, gradio launch: 0.4s).
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale'}
Loading VAE weights specified in settings: /home/voivod/stable-diffusion-webui-forge/models/VAE/sdxl.vae.safetensors
To load target model SDXLClipModel
Begin to load 1 model
Moving model(s) has taken 0.01 seconds
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "/home/voivod/stable-diffusion-webui-forge/launch.py", line 51, in <module>
    main()
  File "/home/voivod/stable-diffusion-webui-forge/launch.py", line 47, in main
    start()
  File "/home/voivod/stable-diffusion-webui-forge/modules/launch_utils.py", line 550, in start
    main_thread.loop()
  File "/home/voivod/stable-diffusion-webui-forge/modules_forge/main_thread.py", line 37, in loop
    task.work()
  File "/home/voivod/stable-diffusion-webui-forge/modules_forge/main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "/home/voivod/stable-diffusion-webui-forge/modules/sd_models.py", line 569, in get_sd_model
    load_model()
  File "/home/voivod/stable-diffusion-webui-forge/modules/sd_models.py", line 720, in load_model
    sd_model.cond_stage_model_empty_prompt = get_empty_cond(sd_model)
  File "/home/voivod/stable-diffusion-webui-forge/modules/sd_models.py", line 596, in get_empty_cond
    d = sd_model.get_learned_conditioning([""])
  File "/home/voivod/stable-diffusion-webui-forge/modules/sd_models_xl.py", line 37, in get_learned_conditioning
    c = self.conditioner(sdxl_conds, force_zero_embeddings=['txt'] if force_zero_negative_prompt else [])
  File "/home/voivod/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/voivod/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/voivod/stable-diffusion-webui-forge/repositories/generative-models/sgm/modules/encoders/modules.py", line 168, in forward
    output[out_key] = torch.cat(
RuntimeError: Promotion for Float8 Types is not supported, attempted to promote Float and Float8_e4m3fn


Stable diffusion model failed to load
```

### Additional information

Recently upgrade webui to the latest version.
Tried to upgrade torch to latest version
Tried with --xformers and --pytorch-attention

**Comment by Panchovix** [comment]
Hi there, thanks for the report. Does this happened on OG Forge as well (before the new updates), or it worked there?

Does it work on dev_upstream branch?

**Comment by ImOnAWatchList** [comment]
Both unet-fp8 flags worked fine for me on an older ReForge commit from before controlnet was updated, on main branch.

**Comment by Panchovix** [comment]
Can you pin point me to that older reforge commit please? Also, maybe you can try upgrading torch to 2.3.1

**Comment by Vektor8298** [comment]
@Panchovix Hi, I "upgraded" from vanilla Forge, so I will try to reinstall reForge and see if that helps.

**Comment by Panchovix** [comment]
Hi there, thanks for the report. That's a weird issue, which torch version do you have installed?

Also did a new branch with some experimental changes, if you want to test there as well https://github.com/Panchovix/stable-diffusion-webui-reForge/commits/dev_upstream_experimental

**Comment by Vektor8298** [comment]
> Hi there, thanks for the report. That's a weird issue, which torch version do you have installed?
> 
> Also did a new branch with some experimental changes, if you want to test there as well https://github.com/Panchovix/stable-diffusion-webui-reForge/commits/dev_upstream_experimental

Thanks @Panchovix I will try, since I have been getting lots of `TypeError: 'NoneType' object is not iterable` errors too, on my 4gb 3050 laptop gpu, which I did ono get before.

**Comment by Vektor8298** [comment]
@Panchovix Tried with `torch 2.4.0`, `2.3.1` CUDA 12 and nothing makes it work, SD 1.5 works fine as I stated.

**Comment by Panchovix** [comment]
I have managed to load in FP8 (I think?) changing the code on the sgm\modules\encoders\modules.py file

```
def forward(
        self, batch: Dict, force_zero_embeddings: Optional[List] = None
    ) -> Dict:
        output = dict()
        if force_zero_embeddings is None:
            force_zero_embeddings = []
        for embedder in self.embedders:
            embedding_context = nullcontext if embedder.is_trainable else torch.no_grad
            with embedding_context():
                if hasattr(embedder, "input_key") and (embedder.input_key is not None):
                    if embedder.legacy_ucg_val is not None:
                        batch = self.possibly_get_ucg_val(embedder, batch)
                    emb_out = embedder(batch[embedder.input_key])
                elif hasattr(embedder, "input_keys"):
                    emb_out = embedder(*[batch[k] for k in embedder.input_keys])
            assert isinstance(
                emb_out, (torch.Tensor, list, tuple)
            ), f"encoder outputs must be tensors or a sequence, but got {type(emb_out)}"
            if not isinstance(emb_out, (list, tuple)):
                emb_out = [emb_out]
            for emb in emb_out:
                out_key = self.OUTPUT_DIM2KEYS[emb.dim()]
                if embedder.ucg_rate > 0.0 and embedder.legacy_ucg_val is None:
                    emb = (
                        expand_dims_like(
                            torch.bernoulli(
                                (1.0 - embedder.ucg_rate)
                                * torch.ones(emb.shape[0], device=emb.device)
                            ),
                            emb,
                        )
                        * emb
                    )
                if (
                    hasattr(embedder, "input_key")
                    and embedder.input_key in force_zero_embeddings
                ):
                    emb = torch.zeros_like(emb)
                if out_key in output:
                    output[out_key] = torch.cat(
                        (output[out_key], emb), self.KEY2CATDIM[out_key]
                    )
                else:
                    output[out_key] = emb
        return output
```

To

```
def forward(
        self, batch: Dict, force_zero_embeddings: Optional[List] = None
    ) -> Dict:
        output = dict()
        if force_zero_embeddings is None:
            force_zero_embeddings = []
        for embedder in self.embedders:
            embedding_context = nullcontext if embedder.is_trainable else torch.no_grad
            with embedding_context():
                if hasattr(embedder, "input_key") and (embedder.input_key is not None):
                    if embedder.legacy_ucg_val is not None:
                        batch = self.possibly_get_ucg_val(embedder, batch)
                    emb_out = embedder(batch[embedder.input_key])
                elif hasattr(embedder, "input_keys"):
                    emb_out = embedder(*[batch[k] for k in embedder.input_keys])
            assert isinstance(
                emb_out, (torch.Tensor, list, tuple)
            ), f"encoder outputs must be tensors or a sequence, but got {type(emb_out)}"
            if not isinstance(emb_out, (list, tuple)):
                emb_out = [emb_out]
            for emb in emb_out:
                out_key = self.OUTPUT_DIM2KEYS[emb.dim()]
                if embedder.ucg_rate > 0.0 and embedder.legacy_ucg_val is None:
                    emb = (
                        expand_dims_like(
                            torch.bernoulli(
                                (1.0 - embedder.ucg_rate)
                                * torch.ones(emb.shape[0], device=emb.device)
                            ),
                            emb,
                        )
                        * emb
                    )
                if (
                    hasattr(embedder, "input_key")
                    and embedder.input_key in force_zero_embeddings
                ):
                    emb = torch.zeros_like(emb)
                if out_key in output:
                    # Convert emb to match output[out_key]'s dtype before concatenation
                    if emb.dtype != output[out_key].dtype:
                        emb = emb.to(output[out_key].dtype)
                    output[out_key] = torch.cat(
                        (output[out_key], emb), self.KEY2CATDIM[out_key]
                    )
                else:
                    output[out_key] = emb
        return output
```

The problem is mostly that repo comes from a external repo, not reforge itself. I could fork it and use it as reference with the fix, but first if someone can test it and works as expected, would be great
