### ISSUE TITLE
[Bug]: ControlNet errors

### ISSUE THREAD

**Issue by LGH-CCC** [Panchovix/stable-diffusion-webui-reForge#126]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

ControlNet is unavailable.
First I used the following model.
https://huggingface.co/bdsqlsz/qinglong_controlnet-lllite/blob/main/bdsqlsz_controlllite_xl_tile_anime_beta.safetensors

I tried several other models, but the results were the same.

### Steps to reproduce the problem

1. open "ControlNet Unit 0"
2. checked "Enable"
3. selected "Tile"
4. selected "tile_colorfix"
5. selected "bdsqlsz_controlllite_xl_tile_anime_beta [2eac70f9]"
6. selected "Balanced" (Initially nothing is selected. It feels like something was selected by default before.)
7. selected "Crop and Resize" (Initially nothing is selected. It feels like something was selected by default before.)
8. selected "Both" (Initially nothing is selected. It feels like something was selected by default before.)
9. Generate

### What should have happened?

An image to which ControlNet is not applied is output.
The same results are output as images without using ControlNet with the same parameters.

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

### Sysinfo

[sysinfo-2024-08-19-11-35.json](https://github.com/user-attachments/files/16659596/sysinfo-2024-08-19-11-35.json)

Using paperspace

### Console logs

```Shell
2024-08-19 11:38:07,957 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
*** Error running process: /notebooks/stable-diffusion-webui-reForge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui-reForge/modules/scripts.py", line 843, in process
        script.process(p, *script_args)
      File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/notebooks/stable-diffusion-webui-reForge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 616, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/notebooks/stable-diffusion-webui-reForge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 355, in process_unit_after_click_generate
        input_list, resize_mode = self.get_input_data(p, unit, preprocessor, h, w)
      File "/notebooks/stable-diffusion-webui-reForge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 260, in get_input_data
        resize_mode = external_code.resize_mode_from_value(p.resize_mode)
    AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'resize_mode'

---

2024-08-19 11:38:09,899 - ControlNet - WARNING - Not enough parameters for all enabled units. Resetting current_params.
*** Error running process: /notebooks/stable-diffusion-webui-reForge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui-reForge/modules/scripts.py", line 843, in process
        script.process(p, *script_args)
      File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/notebooks/stable-diffusion-webui-reForge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 616, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/notebooks/stable-diffusion-webui-reForge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 355, in process_unit_after_click_generate
        input_list, resize_mode = self.get_input_data(p, unit, preprocessor, h, w)
      File "/notebooks/stable-diffusion-webui-reForge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 260, in get_input_data
        resize_mode = external_code.resize_mode_from_value(p.resize_mode)
    AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'resize_mode'

---
```

**Comment by Panchovix** [comment]
Hi there, it seems to happen only when an image is not added, but it seems to be needed as shown on https://github.com/Mikubill/sd-webui-controlnet/pull/1430

You can re open the issue otherwhise
