### ISSUE TITLE
[Bug]: SVD failure

### ISSUE THREAD

**Issue by Daniel23stack** [Panchovix/stable-diffusion-webui-reForge#129]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

The SVD tab consistently generates this error on a fresh install.
I have downloaded the SVD : https://civitai.com/models/207992?modelVersionId=329995
I have included a stack trace:
This may be the fix but I am unsure: https://stackoverflow.com/questions/19929626/init-missing-1-required-positional-argument

### Steps to reproduce the problem

Install the current branch, 
Have the SVD model in the SVD model folder. 
Put in an image, push generate.

### What should have happened?

Should have gotten an output.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-08-21-02-51.json](https://github.com/user-attachments/files/16685397/sysinfo-2024-08-21-02-51.json)

### Console logs

```Shell
`Traceback (most recent call last):
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\Image_AI\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_svd\scripts\forge_svd.py", line 50, in predict
    output_latent = opKSampler.sample(model, sampling_seed, sampling_steps, sampling_cfg,
  File "G:\Image_AI\stable-diffusion-webui-reForge\ldm_patched\contrib\external.py", line 1379, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "G:\Image_AI\stable-diffusion-webui-reForge\ldm_patched\contrib\external.py", line 1349, in common_ksampler
    samples = ldm_patched.modules.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "G:\Image_AI\stable-diffusion-webui-reForge\ldm_patched\modules\sample.py", line 104, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "G:\Image_AI\stable-diffusion-webui-reForge\ldm_patched\modules\samplers.py", line 825, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "G:\Image_AI\stable-diffusion-webui-reForge\ldm_patched\modules\samplers.py", line 719, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "G:\Image_AI\stable-diffusion-webui-reForge\ldm_patched\modules\samplers.py", line 637, in sample
    model_k = KSamplerX0Inpaint(model_wrap)
TypeError: KSamplerX0Inpaint.__init__() missing 1 required positional argument: 'sigmas'`
```

**Comment by Daniel23stack** [comment]
Taking a further look into it.
`File "G:\Image_AI\stable-diffusion-webui-reForge\ldm_patched\modules\samplers.py", line 637, in sample
    model_k = KSamplerX0Inpaint(model_wrap)`
I changed the line so that sigmas would pass as expected. However I recieved the following error:
` File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\Image_AI\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_svd\scripts\forge_svd.py", line 50, in predict
    output_latent = opKSampler.sample(model, sampling_seed, sampling_steps, sampling_cfg,
  File "G:\Image_AI\stable-diffusion-webui-reForge\ldm_patched\contrib\external.py", line 1379, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "G:\Image_AI\stable-diffusion-webui-reForge\ldm_patched\contrib\external.py", line 1349, in common_ksampler
    samples = ldm_patched.modules.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "G:\Image_AI\stable-diffusion-webui-reForge\ldm_patched\modules\sample.py", line 104, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "G:\Image_AI\stable-diffusion-webui-reForge\ldm_patched\modules\samplers.py", line 826, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "G:\Image_AI\stable-diffusion-webui-reForge\ldm_patched\modules\samplers.py", line 720, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "G:\Image_AI\stable-diffusion-webui-reForge\ldm_patched\modules\samplers.py", line 659, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "G:\Image_AI\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\Image_AI\stable-diffusion-webui-reForge\ldm_patched\k_diffusion\sampling.py", line 452, in sample_dpm_2_ancestral
    sigma_down, sigma_up = get_ancestral_step(sigmas[i], sigmas[i + 1], eta=eta)
TypeError: KSamplerX0Inpaint.__call__() got an unexpected keyword argument 'cond'`

**Comment by tERB00** [comment]
I've got the same issue. 

p.s. I believe there is a typo - should be SVD, not SVG?

**Comment by Daniel23stack** [comment]
You are correct I have updated the issue.

**Comment by Kemahudson** [comment]
Having the same problem here as well.

**Comment by jlxsolutions** [comment]
this fork seems to have fixed sampler.py and sd_samplers_cfg_denoiser.py at least partially some samplers say missing "eta" https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/e28637e5a0104da09509956aa3bdf25ca327123f
at least i am not erroring our so far.

**Comment by Vojec** [comment]
> this fork seems to have fixed sampler.py and sd_samplers_cfg_denoiser.py at least partially some samplers say missing "eta" [e28637e](https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/e28637e5a0104da09509956aa3bdf25ca327123f) at least i am not erroring out so far.

Oh big thanks for solution ;)

**Comment by jpanneton** [comment]
I'm still getting the same error in latest main.

**Comment by Panchovix** [comment]
Fixed by https://github.com/Panchovix/stable-diffusion-webui-reForge/pull/254
