### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by asdrabael** [Panchovix/stable-diffusion-webui-reForge#133]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Trying to use the SVD tab returns this error:
TypeError: KSamplerX0Inpaint.__init__() missing 1 required positional argument: 'sigmas'

it doesn't matter what I do or what sampler I use. I get this error. I even resized my picture to the size the extension is set on when I first opened it. I'm at a loss now.

### Steps to reproduce the problem

1.Goto SVD Tab.
2. Put picture into it
3. 3. hit generate

### What should have happened?

webui should have created a short video

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-08-27-10-07.json](https://github.com/user-attachments/files/16760390/sysinfo-2024-08-27-10-07.json)

### Console logs

```Shell
Traceback (most recent call last):
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/extensions-builtin/sd_forge_svd/scripts/forge_svd.py", line 50, in predict
    output_latent = opKSampler.sample(model, sampling_seed, sampling_steps, sampling_cfg,
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/ldm_patched/contrib/external.py", line 1379, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/ldm_patched/contrib/external.py", line 1349, in common_ksampler
    samples = ldm_patched.modules.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/ldm_patched/modules/sample.py", line 104, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/ldm_patched/modules/samplers.py", line 825, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/ldm_patched/modules/samplers.py", line 719, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/asdra/Desktop/forge/stable-diffusion-webui-reForge/ldm_patched/modules/samplers.py", line 637, in sample
    model_k = KSamplerX0Inpaint(model_wrap)
TypeError: KSamplerX0Inpaint.__init__() missing 1 required positional argument: 'sigmas'
```

### Additional information

fresh install

**Comment by rchow93** [comment]
I've also confirmed this error (and bug) with the same settings running from a Windows 11 Machine with 3070 graphics card. I tested all the samplers and the only ones that work are uni_pc and uni_pc_bh2. I tested several pictures with these samplers and scheduler combinations but all came out very poor video rendering. I think there is a bug in the sampler.py file. In the dev branch there are a bunch of changes being added to that file so I think we need to wait for that fix. The alternative is to go to comfyui which I've got running on my Mac and videos look great with the other samplers.

**Comment by BethKothe** [comment]
I am also having this issue running SVD through stability matrix in ReForge.

**Comment by BethKothe** [comment]
I also have it.

```
Traceback (most recent call last):
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\extensions-builtin\sd_forge_svd\scripts\forge_svd.py", line 50, in predict
    output_latent = opKSampler.sample(model, sampling_seed, sampling_steps, sampling_cfg,
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\ldm_patched\contrib\external.py", line 1379, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\ldm_patched\contrib\external.py", line 1349, in common_ksampler
    samples = ldm_patched.modules.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\ldm_patched\modules\sample.py", line 104, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\ldm_patched\modules\samplers.py", line 825, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\ldm_patched\modules\samplers.py", line 719, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "C:\Users\TheSu\OneDrive\Desktop\Data\Packages\Stable Diffusion WebUI reForge\ldm_patched\modules\samplers.py", line 637, in sample
    model_k = KSamplerX0Inpaint(model_wrap)
TypeError: KSamplerX0Inpaint.__init__() missing 1 required positional argument: 'sigmas'
```

**Comment by benjamen** [comment]
Same issue but   File "C:\Users\User\Documents\StabilityMatrix-win-x64\Data\Packages\reforge\ldm_patched\k_diffusion\sampling.py", line 461, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
TypeError: KSamplerX0Inpaint.__call__() got an unexpected keyword argument 'cond'

**Comment by jpanneton** [comment]
Also getting this issue.

**Comment by tERB00** [comment]
For anyone cant get it to work - try DDIM or Uni_pc samplers and schedulers.

**Comment by Panchovix** [comment]
Fixed by https://github.com/Panchovix/stable-diffusion-webui-reForge/pull/254
