### ISSUE TITLE
[Bug]: SAG not working?

### ISSUE THREAD

**Issue by Vantagevoin** [Panchovix/stable-diffusion-webui-reForge#140]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

SAG is not working as intended.

### Steps to reproduce the problem

1. Enable SAG
2. Click Generate

### What should have happened?

SAG should be working.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-09-14-09-59.json](https://github.com/user-attachments/files/17001849/sysinfo-2024-09-14-09-59.json)

### Console logs

```Shell
D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge>git pull
Already up to date.
venv "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f1.0.2-v1.10.1RC-latest-691-g37223711
Commit hash: 372237113a53d2414a8a06dfc6bc267d8f90c5c3
Launching Web UI with arguments: --xformers --pin-shared-memory --cuda-malloc --cuda-stream
Using cudaMallocAsync backend.
Total VRAM 6144 MB, total RAM 14204 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\venv\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
CUDA Stream Activated:  True
D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\venv\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using xformers cross attention
ControlNet preprocessor location: D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\models\ControlNetPreprocessor
D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\venv\lib\site-packages\diffusers\models\transformers\transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
Loading model EasyFluffV11.2.safetensors [821628644e] (1 of 1)
Loading weights [821628644e] from D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\models\Stable-diffusion\EasyFluffV11.2.safetensors
2024-09-14 16:56:44,522 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
model_type EPS
UNet ADM Dimension 0
Startup time: 15.8s (prepare environment: 3.4s, import torch: 5.1s, import gradio: 1.2s, setup paths: 1.4s, initialize shared: 0.4s, other imports: 0.7s, load scripts: 2.4s, create ui: 0.7s, gradio launch: 0.5s).
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
loaded straight to GPU
To load target model BaseModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  3456.593864440918
[Memory Management] Model Memory (MB) =  0.00762939453125
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  2432.5862350463867
Moving model(s) has taken 0.03 seconds
Loading VAE weights specified in settings: D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\models\VAE\furception_vae_1-0.safetensors
To load target model SD1ClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  3455.687026977539
[Memory Management] Model Memory (MB) =  454.20703506469727
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  1977.4799919128418
Moving model(s) has taken 0.12 seconds
Model EasyFluffV11.2.safetensors [821628644e] loaded in 4.4s (load weights from disk: 0.8s, forge load real models: 1.9s, load VAE: 0.4s, load textual inversion embeddings: 1.0s, calculate empty prompt: 0.3s).
To load target model BaseModel
Begin to load 1 model
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  3127.2599201202393
[Memory Management] Model Memory (MB) =  0.00762939453125
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  2103.252290725708
Moving model(s) has taken 0.03 seconds
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\modules\processing.py", line 822, in process_images
    res = process_images_inner(p)
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\modules\processing.py", line 971, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\modules\processing.py", line 1342, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\modules\sd_samplers_kdiffusion.py", line 261, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\modules\sd_samplers_common.py", line 274, in launch_sampling
    return func()
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\modules\sd_samplers_kdiffusion.py", line 261, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\modules\sd_samplers_cfg_denoiser.py", line 223, in forward
    denoised = sampling_function(model, x, sigma, None, cond_patched, 1.0, model_options, seed)
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\ldm_patched\modules\samplers.py", line 334, in sampling_function
    cfg_result = fn(args)
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\ldm_patched\contrib\external_sag.py", line 152, in post_cfg_function
    degraded = create_blur_map(uncond_pred, uncond_attn, sag_sigma, sag_threshold)
  File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\ldm_patched\contrib\external_sag.py", line 58, in create_blur_map
    _, hw1, hw2 = attn.shape
AttributeError: 'NoneType' object has no attribute 'shape'
'NoneType' object has no attribute 'shape'
*** Error completing request
*** Arguments: ('task(eipqjeesm8d6i22)', <gradio.routes.Request object at 0x000001AB316E8CA0>, 'fox', '', [], 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', [], 0, 20, 'DPM++ 2M', 'Automatic', False, '', 0.8, -1, False, -1, 0, 0, 0, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], multi_inputs_gallery=[], generated_image=None, mask_image=None, hr_option=<HiResFixOption.BOTH: 'Both'>, enabled=False, module='None', model='None', weight=1, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, advanced_weighting=None, save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], multi_inputs_gallery=[], generated_image=None, mask_image=None, hr_option=<HiResFixOption.BOTH: 'Both'>, enabled=False, module='None', model='None', weight=1, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, advanced_weighting=None, save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], multi_inputs_gallery=[], generated_image=None, mask_image=None, hr_option=<HiResFixOption.BOTH: 'Both'>, enabled=False, module='None', model='None', weight=1, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, advanced_weighting=None, save_detected_map=True), False, 7, 1, 'Constant', 0, 'Constant', 0, 1, 'enable', 'MEAN', 'AD', 1, False, 1.01, 1.02, 0.99, 0.95, True, 0.5, 2, False, 0.7, False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\New\Sys\Stable Diffusion\stable-diffusion-webui-reForge\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---
```

### Additional information

SAG extension works fine on OG sd-webui. Help?

**Comment by Panchovix** [comment]
This is now fixed on dev/dev2 branches.
