### ISSUE TITLE
[Bug]:  AttributeError: 'UnetPatcher' object has no attribute 'forge_unpatch_model'

### ISSUE THREAD

**Issue by slashedstar** [Panchovix/stable-diffusion-webui-reForge#144]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Extension not working

### Steps to reproduce the problem

Install https://github.com/hako-mikan/sd-webui-lora-block-weight and try to generate a image with the extension enabled, e.g. <lora:lora_name:1:lbw=OUTALL>

### What should have happened?

Should've worked 🤔

### Sysinfo

[sysinfo-2024-10-02-19-55.json](https://github.com/user-attachments/files/17235281/sysinfo-2024-10-02-19-55.json)

### Console logs

```Shell
[LORA] Loaded X:lora\lvlv\lorafiles\lvlv002\lvlv002_r.safetensors for SDXL-UNet with 601 keys at weight 1.0 (skipped 0 keys)
[LORA] Loaded X:lora\lvlv\lorafiles\lvlv002\lvlv002_r.safetensors for SDXL-CLIP with 64 keys at weight 1.0 (skipped 0 keys)
LoRA Block weight (lora): lvlv002_r: (Te:1.0,Unet:1.0) x [1.0, 0, 0, 0, 0, 0.0, 0.0, 0, 0.0, 0.0, 0, 0, 0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0]
*** Error running after_extra_networks_activate: E:\stable-diffusion-webui-reForge\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui-reForge\modules\scripts.py", line 875, in after_extra_networks_activate
        script.after_extra_networks_activate(p, *script_args, **kwargs)
      File "E:\stable-diffusion-webui-reForge\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 541, in after_extra_networks_activate
        loradealer(self, kwargs["prompts"] ,self.lratios,self.elementals,kwargs["extra_network_data"])
      File "E:\stable-diffusion-webui-reForge\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 893, in loradealer
        if go_lbw or load: load_loras_blocks(self, lorans,lorars,te_multipliers,unet_multipliers,elements,ltype, starts=starts)
      File "E:\stable-diffusion-webui-reForge\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 975, in load_loras_blocks
        lora_patches = shared.sd_model.forge_objects_after_applying_lora.unet.lora_patches
    AttributeError: 'UnetPatcher' object has no attribute 'lora_patches'

---
To load target model SDXL
Begin to load 1 model
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  19554.934301376343
[Memory Management] Model Memory (MB) =  3342.8125
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  15188.121801376343
Moving model(s) has taken 0.70 seconds
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21/21 [00:02<00:00,  7.81it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 20/21 [00:02<00:00, 10.97it/s]
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  16203.629613876343
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  15020.072532653809
Moving model(s) has taken 0.05 seconds
*** Error running postprocess: E:\stable-diffusion-webui-reForge\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui-reForge\modules\scripts.py", line 891, in postprocess
        script.postprocess(p, processed, *script_args)
      File "E:\stable-diffusion-webui-reForge\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 530, in postprocess
        shared.sd_model.forge_objects_after_applying_lora.unet.forge_unpatch_model()
    AttributeError: 'UnetPatcher' object has no attribute 'forge_unpatch_model'

---
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00,  6.44it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00, 10.97it/s]
```

**Comment by firsc** [comment]
I had the same problem and I fixed it by checking out an older version of lora block weight. In my case I reached far back with 4d94d247, a commit from April, but maybe a newer one might also work?

```
cd extensions/sd-webui-lora-block-weight
git checkout 4d94d247
```

**Comment by Panchovix** [comment]
fixed lora block weight is now part of reforge. separated extension is not compatible as it deprecated old forge support
