### ISSUE TITLE
[Bug]: Lots of warning & error on fresh git clone install.

### ISSUE THREAD

**Issue by lespaul64** [Panchovix/stable-diffusion-webui-reForge#165]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Is this normal?

### Steps to reproduce the problem

- I have python 3.11.9 installed.
- git clone https://github.com/Panchovix/stable-diffusion-webui-reForge.git
- edit webui-user.bat --> COMMANDLINE_ARGS=--skip-python-version-check --cuda-malloc
- run webui-user.bat, wait until install process done then this warning & error appear.

### What should have happened?

From the error message i believe some controlnet feature will not available.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-11-04-08-16.json](https://github.com/user-attachments/files/17615513/sysinfo-2024-11-04-08-16.json)

### Console logs

```Shell
venv "J:\bot\robot\reforge-p3119\venv\Scripts\Python.exe"
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Version: f1.0.2-v1.10.1RC-latest-702-g363970b5
Commit hash: 363970b50f3824c872b5be11199688f19298a9e0
Installing requirements
Legacy Preprocessor init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.
Launching Web UI with arguments: --skip-python-version-check --cuda-malloc
Using cudaMallocAsync backend.
Total VRAM 8187 MB, total RAM 16254 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
J:\bot\robot\reforge-p3119\venv\Lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
J:\bot\robot\reforge-p3119\venv\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Using pytorch cross attention
*** Error loading script: SC_pipeline.py
    Traceback (most recent call last):
      File "J:\bot\robot\reforge-p3119\modules\scripts.py", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\bot\robot\reforge-p3119\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\bot\robot\reforge-p3119\extensions-builtin\StableCascade-for-webUI-main\scripts\SC_pipeline.py", line 27, in <module>
        from diffusers.models import StableCascadeUNet
      File "J:\bot\robot\reforge-p3119\venv\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "J:\bot\robot\reforge-p3119\venv\Lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
        from .dynamic_modules_utils import get_class_from_dynamic_module
      File "J:\bot\robot\reforge-p3119\venv\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
        from huggingface_hub import cached_download, hf_hub_download, model_info
    ImportError: cannot import name 'cached_download' from 'huggingface_hub' (J:\bot\robot\reforge-p3119\venv\Lib\site-packages\huggingface_hub\__init__.py)

---
*** Error loading script: stablecascade_diffusers.py
    Traceback (most recent call last):
      File "J:\bot\robot\reforge-p3119\modules\scripts.py", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\bot\robot\reforge-p3119\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\bot\robot\reforge-p3119\extensions-builtin\StableCascade-for-webUI-main\scripts\stablecascade_diffusers.py", line 1, in <module>
        from diffusers.utils import check_min_version
      File "J:\bot\robot\reforge-p3119\venv\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "J:\bot\robot\reforge-p3119\venv\Lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
        from .dynamic_modules_utils import get_class_from_dynamic_module
      File "J:\bot\robot\reforge-p3119\venv\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
        from huggingface_hub import cached_download, hf_hub_download, model_info
    ImportError: cannot import name 'cached_download' from 'huggingface_hub' (J:\bot\robot\reforge-p3119\venv\Lib\site-packages\huggingface_hub\__init__.py)

---
ControlNet preprocessor location: J:\bot\robot\reforge-p3119\models\ControlNetPreprocessor
*** Error loading script: preprocessor_marigold.py
    Traceback (most recent call last):
      File "J:\bot\robot\reforge-p3119\modules\scripts.py", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "J:\bot\robot\reforge-p3119\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\bot\robot\reforge-p3119\extensions-builtin\forge_preprocessor_marigold\scripts\preprocessor_marigold.py", line 10, in <module>
        from marigold.model.marigold_pipeline import MarigoldPipeline
      File "J:\bot\robot\reforge-p3119\extensions-builtin\forge_preprocessor_marigold\marigold\model\marigold_pipeline.py", line 9, in <module>
        from diffusers import (
      File "J:\bot\robot\reforge-p3119\venv\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "J:\bot\robot\reforge-p3119\venv\Lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
        from .dynamic_modules_utils import get_class_from_dynamic_module
      File "J:\bot\robot\reforge-p3119\venv\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
        from huggingface_hub import cached_download, hf_hub_download, model_info
    ImportError: cannot import name 'cached_download' from 'huggingface_hub' (J:\bot\robot\reforge-p3119\venv\Lib\site-packages\huggingface_hub\__init__.py)

---
Loading model pony\ponyFaetality_v11.safetensors [499513276a] (1 of 1)
Loading weights [499513276a] from J:\bot\robot\reforge-p3119\models\Stable-diffusion\pony\ponyFaetality_v11.safetensors
2024-11-04 15:19:26,642 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
model_type EPS
UNet ADM Dimension 2816
Startup time: 18.3s (prepare environment: 6.5s, import torch: 5.4s, import gradio: 1.6s, setup paths: 1.3s, initialize shared: 0.2s, other imports: 0.4s, load scripts: 1.6s, create ui: 0.5s, gradio launch: 0.7s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
J:\bot\robot\reforge-p3119\venv\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
To load target model SDXLClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  7086.738372802734
[Memory Management] Model Memory (MB) =  2144.3535232543945
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  3918.38484954834
Moving model(s) has taken 0.88 seconds
Model pony\ponyFaetality_v11.safetensors [499513276a] loaded in 10.9s (load weights from disk: 0.8s, forge load real models: 8.7s, calculate empty prompt: 1.2s).
```

**Comment by metapea** [comment]
Unrelated, but I've also keep getting other errors like:
```
X:\Reforge\system\python\lib\site-packages\tran
sformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_
spaces` was not set. It will be set to `True` by default. This behavior will be
depracted in transformers v4.45, and will be then set to `False` by default. For
 more details check this issue: https://github.com/huggingface/transformers/issu
es/31884
  warnings.warn( 
```

**Comment by Panchovix** [comment]
Hi there, thanks for the report. These issues are because the huggingface_hub got updated and it deprecated that function, it only happens on main branch for some reason. Now should be fixed. The other warnings can be ignored.
