### ISSUE TITLE
[Bug]: Fresh install crashes on startup (AttributeError: 'Options' object has no attribute 'dat_enabled_models')

### ISSUE THREAD

**Issue by nveaa1** [Panchovix/stable-diffusion-webui-reForge#168]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Traceback (most recent call last):
  File "E:\ai_stuff\stable-diffusion-webui-reForge\launch.py", line 51, in <module>
    main()
  File "E:\ai_stuff\stable-diffusion-webui-reForge\launch.py", line 47, in main
    start()
  File "E:\ai_stuff\stable-diffusion-webui-reForge\modules\launch_utils.py", line 542, in start
    import webui
  File "E:\ai_stuff\stable-diffusion-webui-reForge\webui.py", line 23, in <module>
    initialize.initialize()
  File "E:\ai_stuff\stable-diffusion-webui-reForge\modules\initialize.py", line 89, in initialize
    initialize_rest(reload_script_modules=False)
  File "E:\ai_stuff\stable-diffusion-webui-reForge\modules\initialize.py", line 133, in initialize_rest
    modelloader.load_upscalers()
  File "E:\ai_stuff\stable-diffusion-webui-reForge\modules\modelloader.py", line 108, in load_upscalers
    scaler = cls(commandline_model_path)
  File "E:\ai_stuff\stable-diffusion-webui-reForge\modules\dat_model.py", line 22, in __init__
    if model.name in opts.dat_enabled_models:
  File "E:\ai_stuff\stable-diffusion-webui-reForge\modules\options.py", line 142, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'dat_enabled_models'

### Steps to reproduce the problem

1. Get the latest commit
2. Starting the program crashes, whether it's an updated version or a fresh install.

### What should have happened?

WebUI should start without errors.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

I can't load WebUI and starting with --dump-sysinfo crashes on startup with a different error. For the purposes of trying to provide some relevant info in lieu of getting sysinfo, I am using Windows 10 22H2 64-bit and Python 3.10.11 and I am running reForge with an Nvidia GeForce RTX 4070 Super (driver version 566.03) and an AMD Ryzen 9 5950X.

This is the error I get:

E:\ai_stuff\test\stable-diffusion-webui-reForge>webui-user.bat
venv "E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\Scripts\Python.exe"
E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Traceback (most recent call last):
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\launch.py", line 51, in <module>
    main()
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\launch.py", line 29, in main
    filename = launch_utils.dump_sysinfo()
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\launch_utils.py", line 558, in dump_sysinfo
    text = sysinfo.get()
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\sysinfo.py", line 47, in get
    res = get_dict()
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\sysinfo.py", line 120, in get_dict
    "Extensions": get_extensions(enabled=True, fallback_disabled_extensions=config.get('disabled_extensions', [])),
AttributeError: 'str' object has no attribute 'get'
Press any key to continue . . .

### Console logs

```Shell
E:\ai_stuff\test\stable-diffusion-webui-reForge>webui-user.bat
venv "E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f1.0.5-v1.10.1RC-latest-729-g818effd9
Commit hash: 818effd96e5abbd248901f1fd1cabf6c6fd3cdaf
Installing requirements
Launching Web UI with arguments:
Total VRAM 12282 MB, total RAM 65447 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 SUPER : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Using pytorch cross attention
*** Error loading script: SC_pipeline.py
    Traceback (most recent call last):
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\scripts.py", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\extensions-builtin\StableCascade-for-webUI-main\scripts\SC_pipeline.py", line 27, in <module>
        from diffusers.models import StableCascadeUNet
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
        from .dynamic_modules_utils import get_class_from_dynamic_module
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
        from huggingface_hub import cached_download, hf_hub_download, model_info
    ImportError: cannot import name 'cached_download' from 'huggingface_hub' (E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\huggingface_hub\__init__.py)

---
*** Error loading script: stablecascade_diffusers.py
    Traceback (most recent call last):
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\scripts.py", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\extensions-builtin\StableCascade-for-webUI-main\scripts\stablecascade_diffusers.py", line 1, in <module>
        from diffusers.utils import check_min_version
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
        from .dynamic_modules_utils import get_class_from_dynamic_module
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
        from huggingface_hub import cached_download, hf_hub_download, model_info
    ImportError: cannot import name 'cached_download' from 'huggingface_hub' (E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\huggingface_hub\__init__.py)

---
ControlNet preprocessor location: E:\ai_stuff\test\stable-diffusion-webui-reForge\models\ControlNetPreprocessor
*** Error loading script: preprocessor_marigold.py
    Traceback (most recent call last):
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\scripts.py", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\extensions-builtin\forge_preprocessor_marigold\scripts\preprocessor_marigold.py", line 10, in <module>
        from marigold.model.marigold_pipeline import MarigoldPipeline
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\extensions-builtin\forge_preprocessor_marigold\marigold\model\marigold_pipeline.py", line 9, in <module>
        from diffusers import (
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\diffusers\__init__.py", line 5, in <module>
        from .utils import (
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
        from .dynamic_modules_utils import get_class_from_dynamic_module
      File "E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
        from huggingface_hub import cached_download, hf_hub_download, model_info
    ImportError: cannot import name 'cached_download' from 'huggingface_hub' (E:\ai_stuff\test\stable-diffusion-webui-reForge\venv\lib\site-packages\huggingface_hub\__init__.py)

---
Traceback (most recent call last):
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\launch.py", line 51, in <module>
    main()
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\launch.py", line 47, in main
    start()
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\launch_utils.py", line 542, in start
    import webui
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\webui.py", line 23, in <module>
    initialize.initialize()
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\initialize.py", line 89, in initialize
    initialize_rest(reload_script_modules=False)
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\initialize.py", line 133, in initialize_rest
    modelloader.load_upscalers()
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\modelloader.py", line 108, in load_upscalers
    scaler = cls(commandline_model_path)
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\dat_model.py", line 22, in __init__
    if model.name in opts.dat_enabled_models:
  File "E:\ai_stuff\test\stable-diffusion-webui-reForge\modules\options.py", line 142, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'dat_enabled_models'
Press any key to continue . . .
```

### Additional information

This only happened after one of the latest commits on November 9, 2024.

**Comment by gwhitez** [comment]
same thing, I temporarily fixed it by going back to another commit with `git reset --hard dc1ba3958585eae9f4e4e4bff21702efbea228a29bfe`

**Comment by Paharven-Salin** [comment]
Same issue here - 09.11.24 - AttributeError: 'Options' object has no attribute 'dat_enabled_models'
Press any key to continue . . .

**Comment by nveaa1** [comment]
It appears that commit 87fc933 (Fix DAT models download) is what broke startup. No idea what broke --dump_sysinfo though.

**Comment by Mr-ex777** [comment]
> same thing, I temporarily fixed it by going back to another commit with `git reset --hard dc1ba3958585eae9f4e4e4bff21702efbea228a29bfe`

Where do I type that? I tried in the reforge root it just gives me a fatal ambiguous argument error.

**Comment by Panchovix** [comment]
Should be fixed now on latest commit, sorry!

Couldn't fix it faster because got a power outage.

**Comment by Paharven-Salin** [comment]
> Should be fixed now on latest commit, sorry!
> 
> Couldn't fix it faster because got a power outage.

Nice and quick response - thank you and please feel appreciated - **you are!**

**Comment by gwhitez** [comment]
> Where do I type that? I tried in the reforge root it just gives me a fatal ambiguous argument error.

Go to the folder where reforge is installed (stable-diffusion-webui-reForge) open a cmd and put git reset --hard dc1ba3958585eae9f4e4e4e4bff21702efbea228a29bfe
That reverts to a previous version, although it seems to be fixed now.
