### ISSUE TITLE
[Bug]: Loras not working

### ISSUE THREAD

**Issue by wensleyoliv** [Panchovix/stable-diffusion-webui-reForge#18]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

After updating not a single lora is working, it worked before.

### Steps to reproduce the problem

Just use any lora, it gives a error.

### What should have happened?

The lora should just work like before.

### Sysinfo

[sysinfo-2024-07-15-01-31.json](https://github.com/user-attachments/files/16229371/sysinfo-2024-07-15-01-31.json)

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.18v1.10.0RC-latest-572-g26bc9246
Commit hash: 26bc9246c1099de31c251fedb9473a0155ac4d65
Pulled changes for repository in 'D:\webui_forge\webui\extensions\a1111-sd-webui-tagcomplete':
Already up to date.

Pulled changes for repository in 'D:\webui_forge\webui\extensions\adetailer':
Already up to date.

Pulled changes for repository in 'D:\webui_forge\webui\extensions\Euler-Smea-Dyn-Sampler':
Already up to date.

Pulled changes for repository in 'D:\webui_forge\webui\extensions\sd-civitai-browser-plus':
Already up to date.

Pulled changes for repository in 'D:\webui_forge\webui\extensions\sd-forge-couple':
Already up to date.

Pulled changes for repository in 'D:\webui_forge\webui\extensions\sd-forge-layerdiffuse':
Already up to date.

Pulled changes for repository in 'D:\webui_forge\webui\extensions\sd-perturbed-attention':
Already up to date.

Pulled changes for repository in 'D:\webui_forge\webui\extensions\sd-webui-ar_xhox':
Already up to date.

Pulled changes for repository in 'D:\webui_forge\webui\extensions\sd-webui-diffusion-cg':
Already up to date.

Pulled changes for repository in 'D:\webui_forge\webui\extensions\sd-webui-prompt-format':
Already up to date.

Pulled changes for repository in 'D:\webui_forge\webui\extensions\sd-webui-token-downsampling':
Already up to date.

Pulled changes for repository in 'D:\webui_forge\webui\extensions\sdwebui-close-confirmation-dialogue':
Already up to date.

Pulled changes for repository in 'D:\webui_forge\webui\extensions\stable-diffusion-webui-wildcards':
Already up to date.

Pulled changes for repository in 'D:\webui_forge\webui\extensions\z-a1111-sd-webui-dtg':
Already up to date.

Launching Web UI with arguments: '--ckpt-dir=C:\ComfyUI_windows_portable\ComfyUI\models\checkpoints' '--lora-dir=C:\ComfyUI_windows_portable\ComfyUI\models\loras' --xformers --vae-in-fp16 --update-all-extensions '--vae-dir=C:\ComfyUI_windows_portable\ComfyUI\models\vae' --cuda-malloc --cuda-stream
Using cudaMallocAsync backend.
Total VRAM 6144 MB, total RAM 16335 MB
CUDA Stream Activated:  True
Using xformers cross attention
ControlNet preprocessor location: D:\webui_forge\webui\models\ControlNetPreprocessor
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.6.0, num models: 14
CivitAI Browser+: Aria2 RPC started
Loading model autismmixSDXL_autismmixConfetti.safetensors [ac006fdd7e] (1 out of 1)
Loading weights [ac006fdd7e] from C:\ComfyUI_windows_portable\ComfyUI\models\checkpoints\autismmixSDXL_autismmixConfetti.safetensors
2024-07-14 22:30:29,756 - ControlNet - INFO - ControlNet UI callback registered.
First weight key found: conditioner.embedders.0.transformer.text_model.embeddings.position_embedding.weight
model_type EPS
UNet ADM Dimension 2816
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 129.5s (initial startup: 0.2s, prepare environment: 42.0s, import torch: 40.3s, import gradio: 10.9s, setup paths: 5.3s, initialize shared: 1.0s, other imports: 6.7s, setup gfpgan: 0.2s, list SD models: 0.6s, load scripts: 16.1s, load upscalers: 0.1s, create ui: 4.7s, gradio launch: 1.4s, add APIs: 0.5s).
clip missing: ['clip_l.text_projection', 'clip_l.logit_scale', 'clip_g.transformer.text_model.embeddings.position_ids']
Loading VAE weights specified in settings: C:\ComfyUI_windows_portable\ComfyUI\models\vae\sdxl_vae.safetensors
Model loaded in 50.4s (calculate hash: 0.1s, load weights from disk: 0.9s, forge instantiate config: 3.4s, forge load real models: 28.0s, forge finalize: 1.7s, load VAE: 2.0s, load textual inversion embeddings: 0.6s, calculate empty prompt: 13.6s).
[LORA] Loaded C:\ComfyUI_windows_portable\ComfyUI\models\loras\Expressive_H-000001.safetensors for SDXL-UNet with 722 keys at weight 1.0
[LORA] Loaded C:\ComfyUI_windows_portable\ComfyUI\models\loras\Expressive_H-000001.safetensors for SDXL-CLIP with 264 keys at weight 1.0
  0%|                                                                                           | 0/30 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "D:\webui_forge\webui\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\webui_forge\webui\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\webui_forge\webui\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "D:\webui_forge\webui\modules\processing.py", line 815, in process_images
    res = process_images_inner(p)
  File "D:\webui_forge\webui\modules\processing.py", line 988, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\webui_forge\webui\modules\processing.py", line 1362, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\webui_forge\webui\modules\sd_samplers_kdiffusion.py", line 236, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\webui_forge\webui\modules\sd_samplers_common.py", line 274, in launch_sampling
    return func()
  File "D:\webui_forge\webui\modules\sd_samplers_kdiffusion.py", line 236, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\webui_forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\webui_forge\webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\webui_forge\webui\modules\sd_samplers_cfg_denoiser.py", line 367, in forward
    denoised = sampling_function(model, x, sigma, None, cond_patched, 1.0, model_options, seed)
  File "D:\webui_forge\webui\ldm_patched\modules\samplers.py", line 290, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "D:\webui_forge\webui\ldm_patched\modules\samplers.py", line 259, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "D:\webui_forge\webui\ldm_patched\modules\model_base.py", line 96, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "D:\webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\webui_forge\webui\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 886, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "D:\webui_forge\webui\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 49, in forward_timestep_embed
    x = layer(x, emb, transformer_options)
  File "D:\webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\webui_forge\webui\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 244, in forward
    return checkpoint(
  File "D:\webui_forge\webui\ldm_patched\ldm\modules\diffusionmodules\util.py", line 194, in checkpoint
    return func(*inputs)
  File "D:\webui_forge\webui\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 294, in _forward
    h = self.out_layers(h)
  File "D:\webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\webui_forge\system\python\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\webui_forge\system\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\webui_forge\system\python\lib\site-packages\torch\nn\modules\activation.py", line 396, in forward
    return F.silu(input, inplace=self.inplace)
  File "D:\webui_forge\system\python\lib\site-packages\torch\nn\functional.py", line 2102, in silu
    return torch._C._nn.silu(input)
torch.cuda.OutOfMemoryError: Allocation on device
Allocation on device
*** Error completing request
*** Arguments: ('task(hlhpiur4ugz8ex5)', <gradio.routes.Request object at 0x0000024AD3487A30>, 'score_9, score_8_up, score_7_up, score_6_up, score_5_up, score_4_up, 1girl, <lora:Expressive_H-000001:1> ', 'lowres, bad hands, missing fingers, bad anatomy, fused fingers, bad quality, worst quality, monochrome, 3d', [], 1, 1, 7, 1216, 832, False, 0.3, 1.5, '4xNomos8kSCHAT-L', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', [], 0, 30, 'Euler a', 'Automatic', False, '', 0.8, -1, False, -1, 0, 0, 0, True, False, {'ad_model': 'face_yolov8n_v2.pt', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 2, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'Merge', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': True, 'ad_inpaint_width': 1024, 'ad_inpaint_height': 1024, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': True, 'ad_sampler': 'Euler a', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, False, 'Basic', '', 'Horizontal', 'None', 0.5, [['0.00:0.50', '0.00:1.00', '1.0'], ['0.50:1.00', '0.00:1.00', '1.0']], False, '(SDXL) Only Generate Transparent Image (Attention Injection)', 1, 1, None, None, None, 'Crop and Resize', False, '', '', '', True, 3, 0, 'full', 0, 'middle', 0, '', False, 7, 3, 0, 'full', 0, -1.0, -1.0, False, '1.5', 0, False, 0.01, 0.5, -0.13, 0, 0, 0, 0, False, 'After applying other prompt processings', -1.0, 'short', '2koma, 4koma, artist name, patreon, twitter username, greyscale, monochrome, english text, watermark, patreon logo, web address, censored, mosaic censoring, bar censor', '<|special|>, \n<|characters|>, <|copyrights|>, \n<|artist|>, \n\n<|general|>, \n\n<|quality|>, <|meta|>, <|rating|>', 1.2, 0.9, 90, 'KBlueLeaf/DanTagGen-delta-rev2 | ggml-model-Q8_0.gguf', False, False, ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], multi_inputs_gallery=[], generated_image=None, mask_image=None, hr_option=<HiResFixOption.BOTH: 'Both'>, enabled=False, module='None', model='None', weight=1, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], multi_inputs_gallery=[], generated_image=None, mask_image=None, hr_option=<HiResFixOption.BOTH: 'Both'>, enabled=False, module='None', model='None', weight=1, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, save_detected_map=True), ControlNetUnit(input_mode=<InputMode.SIMPLE: 'simple'>, use_preview_as_input=False, batch_image_dir='', batch_mask_dir='', batch_input_gallery=[], batch_mask_gallery=[], multi_inputs_gallery=[], generated_image=None, mask_image=None, hr_option=<HiResFixOption.BOTH: 'Both'>, enabled=False, module='None', model='None', weight=1, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, save_detected_map=True), False, 6, 0.95, 'Half Cosine Up', 3, 'Half Cosine Up', 3, 1, 'enable', 'MEAN', 'AD', 1, False, 1.4, 0.8, 0.9, 0.2, False, 0.5, 2, False, 256, 2, 0, False, False, 3, 2, 0, 0.35, True, 'bicubic', 'bicubic', False, 0, 'anisotropic', 0, 'reinhard', 100, 0, 'subtract', 0, 0, 'gaussian', 'add', 0, 100, 127, 0, 'hard_clamp', 5, 0, 'None', 'None', False, 'MultiDiffusion', 768, 768, 64, 4, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\webui_forge\webui\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---
```

**Comment by Panchovix** [comment]
What GPU do you have? Wondering why that issue rose.

Here works as expected.

```
Startup time: 47.7s (prepare environment: 12.3s, import torch: 4.4s, import gradio: 1.1s, setup paths: 3.5s, initialize shared: 0.1s, other imports: 0.4s, load scripts: 9.8s, scripts before_ui_callback: 2.4s, create ui: 7.5s, gradio launch: 4.3s, add APIs: 1.2s, app_started_callback: 0.4s).
[LORA] Loaded K:\LoRA_cosas\Lora\styles\KelvinHiu_Style-10.safetensors for SDXL-UNet with 722 keys at weight 1.0
[LORA] Loaded K:\LoRA_cosas\Lora\styles\KelvinHiu_Style-10.safetensors for SDXL-CLIP with 264 keys at weight 1.0
 20%|████████████████▌                                                                  | 5/25 [00:00<00:02,  7.30it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  7.68it/s]
postprocess_batch00%|██████████████████████████████████████████████████████████████████| 25/25 [00:02<00:00,  7.98it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  6.65it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  7.98it/s]
```

**Comment by wensleyoliv** [comment]
I use an RTX 2060 6gb, i dont know if i reverted to this commit the correct way, i used git reset 6ec3abd, please tell me if i did it wrong.

It still gives me errors but a different one,

with Perturbed-Attention Guidance enabled, which i always used it gives an additional error
```
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001B678F7EEC0>]: AttributeError
Traceback (most recent call last):
  File "D:\webui_forge\webui\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\webui_forge\webui\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "D:\webui_forge\webui\extensions-builtin\Lora\networks.py", line 96, in load_networks
    current_sd.forge_objects.unet, current_sd.forge_objects.clip = load_lora_for_models(
  File "D:\webui_forge\webui\ldm_patched\modules\sd.py", line 79, in load_lora_for_models
    new_model = model.clone() if model is not None else None
  File "D:\webui_forge\webui\modules_forge\unet_patcher.py", line 27, in clone
    n.model_keys = self.model_keys
AttributeError: 'UnetPatcher' object has no attribute 'model_keys'

*** Error running process_before_every_sampling: D:\webui_forge\webui\extensions\sd-perturbed-attention\scripts\pag.py
    Traceback (most recent call last):
      File "D:\webui_forge\webui\modules\scripts.py", line 885, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\webui_forge\webui\extensions\sd-perturbed-attention\scripts\pag.py", line 95, in process_before_every_sampling
        unet = opPerturbedAttention.patch(unet, scale, adaptive_scale, block, block_id, sigma_start, sigma_end, rescale_pag, rescale_mode, block_list)[0]
      File "D:\webui_forge\webui\extensions\sd-perturbed-attention\pag_nodes.py", line 110, in patch
        m = model.clone()
      File "D:\webui_forge\webui\modules_forge\unet_patcher.py", line 27, in clone
        n.model_keys = self.model_keys
    AttributeError: 'UnetPatcher' object has no attribute 'model_keys'

---
*** Error running process_before_every_sampling: D:\webui_forge\webui\extensions\sd-perturbed-attention\scripts\pag.py
    Traceback (most recent call last):
      File "D:\webui_forge\webui\modules\scripts.py", line 885, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\webui_forge\webui\extensions\sd-perturbed-attention\scripts\pag.py", line 95, in process_before_every_sampling
        unet = opPerturbedAttention.patch(unet, scale, adaptive_scale, block, block_id, sigma_start, sigma_end, rescale_pag, rescale_mode, block_list)[0]
      File "D:\webui_forge\webui\extensions\sd-perturbed-attention\pag_nodes.py", line 110, in patch
        m = model.clone()
      File "D:\webui_forge\webui\modules_forge\unet_patcher.py", line 27, in clone
        n.model_keys = self.model_keys
    AttributeError: 'UnetPatcher' object has no attribute 'model_keys'

---
```
Without PAG
```
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001B678F9A740>]: AttributeError
Traceback (most recent call last):
  File "D:\webui_forge\webui\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\webui_forge\webui\extensions-builtin\Lora\extra_networks_lora.py", line 43, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "D:\webui_forge\webui\extensions-builtin\Lora\networks.py", line 96, in load_networks
    current_sd.forge_objects.unet, current_sd.forge_objects.clip = load_lora_for_models(
  File "D:\webui_forge\webui\ldm_patched\modules\sd.py", line 79, in load_lora_for_models
    new_model = model.clone() if model is not None else None
  File "D:\webui_forge\webui\modules_forge\unet_patcher.py", line 27, in clone
    n.model_keys = self.model_keys
AttributeError: 'UnetPatcher' object has no attribute 'model_keys'
```

**Comment by Panchovix** [comment]
I personally use git checkout, so

`git checkout 6ec3abd`

Should work.

If not, you can do

`git checkout 2297ab5` which reverts to https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/2297ab5ce19c55dc81cf98a54318bb1cabdc645c commit, which is everything before any comfy upstream changes.

**Comment by wensleyoliv** [comment]
Thank you!
git checkout 6ec3abd still gave the same errors as above, but git checkout 2297ab5 worked perfectly as before.
I will not update for now, you decide if you want to close the issue, as it's tecnically not solved.

**Comment by Panchovix** [comment]
Yeah don't worry, keep it open. But I think I will have the main "dev_upstream_a1111" branch with the update up to the one you got working, and another one named "dev_upstream_a1111_comfy" with all the new but maybe breaking features.

**Comment by Panchovix** [comment]
I have applied the changes, now main has the normal A1111 upstream changes, and dev_upstream has the comfy upstream changes.

For more info, see here https://github.com/Panchovix/stable-diffusion-webui-reForge/discussions/20

I also added some new optimizations if you want to test the dev_upstream branch! :)
