### ISSUE TITLE
[Bug]: sd-forge-couple isn't showing up

### ISSUE THREAD

**Issue by metapea** [Panchovix/stable-diffusion-webui-reForge#180]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

 In the least version of reForge, sd-forge-couple isn't showing up at all now.

### Steps to reproduce the problem

1. Start reForge
2. Install the extension "[sd-forge-couple](https://github.com/Haoming02/sd-forge-couple)"
3. Restart
![Screenshot12](https://github.com/user-attachments/assets/8b30e2b6-b0d2-40c8-983a-5b519e0ee343)

### What should have happened?

For the sd-forge-couple side bar to be under ADetailer.

### What browsers do you use to access the UI ?

Mozilla Firefox, Other

### Sysinfo

Extension version: Newest
OS: Win7
SD-WebUI version: Reforge
Python: 3.10.6

### Console logs

```Shell
*** Error loading script: forge_couple.py
    Traceback (most recent call last):
      File "X:\Reforge\webui\modules\scripts.py
", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "X:\Reforge\webui\modules\script_loa
ding.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_remov
ed
      File "X:\Reforge\webui\extensions\sd-forg
e-couple\scripts\forge_couple.py", line 13, in <module>
        from lib_couple.ui import couple_ui
      File "X:\Reforge\webui\extensions\sd-forg
e-couple\lib_couple\ui.py", line 2, in <module>
        from .ui_adv import advanced_ui
      File "X:\Reforge\webui\extensions\sd-forg
e-couple\lib_couple\ui_adv.py", line 12, in <module>
        PresetManager.load_presets()
      File "X:\Reforge\webui\extensions\sd-forg
e-couple\lib_couple\adv_presets.py", line 17, in load_presets
        cls.presets = load(json_file)
      File "json\__init__.py", line 293, in load
      File "json\__init__.py", line 346, in loads
      File "json\decoder.py", line 337, in decode
      File "json\decoder.py", line 355, in raw_decode
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Panchovix** [comment]
Do you get an error when opening the webui related to the extension?

**Comment by metapea** [comment]
> It was working with updates after august as well. It's only now the extension stopped working. I will looking into rolling back the extension but there isn't a clear way to do so from the webUI.

Tested and https://github.com/Haoming02/sd-forge-couple/commit/3925bc756e6bb221ee2b6326aea1594d40519953 is the last working version for Reforge

**Comment by metapea** [comment]
> Do you get an error when opening the webui related to the extension?

Actually yeah:

```
*** Error loading script: forge_couple.py
    Traceback (most recent call last):
      File "X:/Reforge\webui\modules\scripts.py
", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "X:/Reforge\webui\modules\script_loa
ding.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_remov
ed
      File "X:/Reforge\webui\extensions\sd-forg
e-couple\scripts\forge_couple.py", line 13, in <module>
        from lib_couple.ui import couple_ui
      File "X:/Reforge\webui\extensions\sd-forg
e-couple\lib_couple\ui.py", line 2, in <module>
        from .ui_adv import advanced_ui
      File "X:/Reforge\webui\extensions\sd-forg
e-couple\lib_couple\ui_adv.py", line 12, in <module>
        PresetManager.load_presets()
      File "X:/Reforge\webui\extensions\sd-forg
e-couple\lib_couple\adv_presets.py", line 17, in load_presets
        cls.presets = load(json_file)
      File "json\__init__.py", line 293, in load
      File "json\__init__.py", line 346, in loads
      File "json\decoder.py", line 337, in decode
      File "json\decoder.py", line 355, in raw_decode
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
i thought it was some CivitAI Browser+ error since it was under it

**Comment by metapea** [comment]
The solution was found, the `presets.json` file on the sd-forge-couple folder needed to be deleted.
It works now.
