### ISSUE TITLE
[Bug]: Adetailer not working (FileNotFoundError: path not found: '/tmp/ultralytics_runner')

### ISSUE THREAD

**Issue by Slunkee** [Panchovix/stable-diffusion-webui-reForge#196]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Adetailer not working due to file not found error

### Steps to reproduce the problem

1. open reforge
2. enable adetailer
3. generate

### What should have happened?

Adetailer should work

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-12-05-20-15.json](https://github.com/user-attachments/files/18029118/sysinfo-2024-12-05-20-15.json)

### Console logs

```Shell
venv "E:\a webui-reforge\stable-diffusion-webui-reForge\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f1.1.0-v1.10.1RC-latest-839-gde03257f
Commit hash: de03257f8eee0910b418435000bbe2dd6f424ab7
Launching Web UI with arguments: --pin-shared-memory --cuda-malloc --cuda-stream
Using cudaMallocAsync backend.
Total VRAM 24576 MB, total RAM 32680 MB
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
CUDA Stream Activated:  True
E:\a webui-reforge\stable-diffusion-webui-reForge\venv\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
E:\a webui-reforge\stable-diffusion-webui-reForge\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Using pytorch cross attention
ControlNet preprocessor location: E:\a webui-reforge\stable-diffusion-webui-reForge\models\ControlNetPreprocessor
E:\a webui-reforge\stable-diffusion-webui-reForge\venv\lib\site-packages\diffusers\models\transformers\transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
[-] ADetailer initialized. version: 24.6.0, num models: 10
Loading model realisticVisionV51_v51VAE.safetensors [15012c538f] (1 of 1)
Loading weights [15012c538f] from E:\a webui-reforge\stable-diffusion-webui-reForge\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors
2024-12-05 22:17:48,324 - ControlNet - INFO - ControlNet UI callback registered.
model_type EPS
UNet ADM Dimension 0
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 15.2s (prepare environment: 3.2s, import torch: 5.4s, import gradio: 1.0s, setup paths: 1.2s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 2.5s, create ui: 0.8s, gradio launch: 0.3s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
E:\a webui-reforge\stable-diffusion-webui-reForge\venv\lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
loaded straight to GPU
To load target model BaseModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  21612.593864440918
[Memory Management] Model Memory (MB) =  0.00762939453125
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  20588.586235046387
Moving model(s) has taken 0.01 seconds
To load target model SD1ClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  21612.585647583008
[Memory Management] Model Memory (MB) =  454.20703506469727
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  20134.37861251831
Moving model(s) has taken 0.18 seconds
Model realisticVisionV51_v51VAE.safetensors [15012c538f] loaded in 3.6s (load weights from disk: 0.1s, forge load real models: 3.1s, calculate empty prompt: 0.3s).
Downloading VAEApprox model to: E:\a webui-reforge\stable-diffusion-webui-reForge\models\VAE-approx\model.pt
100%|███████████████████████████████████████████████████████████████████████████████| 209k/209k [00:00<00:00, 6.16MB/s]
To load target model BaseModel
Begin to load 1 model
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  21047.574556350708
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  20023.574556350708
Moving model(s) has taken 0.02 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  7.92it/s]
To load target model AutoencoderKL█████████████████████████████████████████████████████| 20/20 [00:01<00:00, 10.30it/s]
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  21258.031770706177
[Memory Management] Model Memory (MB) =  159.55708122253418
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  20074.474689483643
Moving model(s) has taken 0.04 seconds
curl: (23) client returned ERROR on write of 124 bytes
*** Error running postprocess_image: E:\a webui-reforge\stable-diffusion-webui-reForge\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "E:\a webui-reforge\stable-diffusion-webui-reForge\modules\scripts.py", line 948, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "E:\a webui-reforge\stable-diffusion-webui-reForge\extensions\adetailer\aaaaaa\traceback.py", line 173, in wrapper
        raise error from None
    FileNotFoundError:
    ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │                                                   System info                                                    │
    │ ┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
    │ ┃             ┃ Value                                                                                          ┃ │
    │ ┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
    │ │    Platform │ Windows-10-10.0.19045-SP0                                                                      │ │
    │ │      Python │ 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]             │ │
    │ │     Version │ f1.1.0-v1.10.1RC-latest-839-gde03257f                                                          │ │
    │ │      Commit │ de03257f8eee0910b418435000bbe2dd6f424ab7                                                       │ │
    │ │ Commandline │ ['launch.py', '--pin-shared-memory', '--cuda-malloc', '--cuda-stream']                         │ │
    │ │   Libraries │ {'torch': '2.3.1+cu121', 'torchvision': '0.18.1+cu121', 'ultralytics': '8.3.41', 'mediapipe':  │ │
    │ │             │ '0.10.14'}                                                                                     │ │
    │ └─────────────┴────────────────────────────────────────────────────────────────────────────────────────────────┘ │
    │                                  Inputs                                                                          │
    │ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                         │
    │ ┃                 ┃ Value                                              ┃                                         │
    │ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩                                         │
    │ │          prompt │                                                    │                                         │
    │ │ negative_prompt │                                                    │                                         │
    │ │          n_iter │ 1                                                  │                                         │
    │ │      batch_size │ 1                                                  │                                         │
    │ │           width │ 512                                                │                                         │
    │ │          height │ 512                                                │                                         │
    │ │    sampler_name │ DPM++ 2M                                           │                                         │
    │ │       enable_hr │ False                                              │                                         │
    │ │     hr_upscaler │ Latent                                             │                                         │
    │ │      checkpoint │ realisticVisionV51_v51VAE.safetensors [15012c538f] │                                         │
    │ │             vae │ Automatic                                          │                                         │
    │ │            unet │ Automatic                                          │                                         │
    │ └─────────────────┴────────────────────────────────────────────────────┘                                         │
    │                 ADetailer                                                                                        │
    │ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓                                                                        │
    │ ┃                     ┃ Value           ┃                                                                        │
    │ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩                                                                        │
    │ │             version │ 24.6.0          │                                                                        │
    │ │            ad_model │ face_yolov8n.pt │                                                                        │
    │ │           ad_prompt │                 │                                                                        │
    │ │  ad_negative_prompt │                 │                                                                        │
    │ │ ad_controlnet_model │ None            │                                                                        │
    │ │              is_api │ False           │                                                                        │
    │ └─────────────────────┴─────────────────┘                                                                        │
    │ ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮             │
    │ │ E:\a webui-reforge\stable-diffusion-webui-reForge\extensions\adetailer\aaaaaa\traceback.py:153   │             │
    │ │ in wrapper                                                                                       │             │
    │ │                                                                                                  │             │
    │ │   152 │   │   try:                                                                               │             │
    │ │ ❱ 153 │   │   │   return func(*args, **kwargs)                                                   │             │
    │ │   154 │   │   except Exception as e:                                                             │             │
    │ │                                                                                                  │             │
    │ │ E:\a webui-reforge\stable-diffusion-webui-reForge\extensions\adetailer\scripts\!adetailer.py:818 │             │
    │ │ in postprocess_image                                                                             │             │
    │ │                                                                                                  │             │
    │ │    817 │   │   │   │   │   continue                                                              │             │
    │ │ ❱  818 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)           │             │
    │ │    819                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ E:\a webui-reforge\stable-diffusion-webui-reForge\extensions\adetailer\scripts\!adetailer.py:739 │             │
    │ │ in _postprocess_image_inner                                                                      │             │
    │ │                                                                                                  │             │
    │ │    738 │   │   with change_torch_load():                                                         │             │
    │ │ ❱  739 │   │   │   pred = predictor(ad_model, pp.image, args.ad_confidence, **kwargs)            │             │
    │ │    740                                                                                           │             │
    │ │                                                                                                  │             │
    │ │ E:\a                                                                                             │             │
    │ │ webui-reforge\stable-diffusion-webui-reForge\extensions\adetailer\adetailer\ultralytics.py:27 in │             │
    │ │ ultralytics_predict                                                                              │             │
    │ │                                                                                                  │             │
    │ │   26 │                                                                                           │             │
    │ │ ❱ 27 │   model = YOLO(model_path)                                                                │             │
    │ │   28 │   apply_classes(model, model_path, classes)                                               │             │
    │ │                                                                                                  │             │
    │ │ E:\a                                                                                             │             │
    │ │ webui-reforge\stable-diffusion-webui-reForge\venv\lib\site-packages\ultralytics\models\yolo\mode │             │
    │ │ l.py:26 in __init__                                                                              │             │
    │ │                                                                                                  │             │
    │ │    25 │   │   │   )                                                                              │             │
    │ │ ❱  26 │   │   │   safe_run("/tmp/ultralytics_runner")                                            │             │
    │ │    27 │   │   elif "Darwin" in environment and "arm64" in platform.machine():                    │             │
    │ │                                                                                                  │             │
    │ │ E:\a                                                                                             │             │
    │ │ webui-reforge\stable-diffusion-webui-reForge\venv\lib\site-packages\ultralytics\utils\downloads. │             │
    │ │ py:283 in safe_run                                                                               │             │
    │ │                                                                                                  │             │
    │ │   282 │   """                                                                                    │             │
    │ │ ❱ 283 │   os.chmod(path, 0o770)                                                                  │             │
    │ │   284 │   command = [                                                                            │             │
    │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯             │
    │ FileNotFoundError: [WinError 3] Määritettyä polkua ei löydy: '/tmp/ultralytics_runner'                           │
    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.44it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00, 10.30it/s]
```

**Comment by Panchovix** [comment]
ultralytics on latest versions got compromised, you can see more

https://github.com/ultralytics/ultralytics/issues/18027

Please, on your venv, uninstall latest uiltralytics version and install 8.3.40 or older

**Comment by Slunkee** [comment]
yep, works now. one of those things you never expect to be the cause of an issue
