### ISSUE TITLE
[Bug]:  Problems Warning "HF_HOME - timm.layers"

### ISSUE THREAD

**Issue by JavadZohani** [Panchovix/stable-diffusion-webui-reForge#202]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

After new pip updates, problems occur and there are always warnings to fix this problem. I have been looking for a solution to this problem for a long time and have tried solutions, but it causes new problems. That's why I want you to fix these problems in the new eternity if possible.

D:\AI\Packages\reForge\venv\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
D:\AI\Packages\reForge\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Using pytorch cross attention

### Steps to reproduce the problem

D:\AI\Packages\reForge\venv\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
D:\AI\Packages\reForge\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Using pytorch cross attention

Package
WebUI reForge

When did the issue occur?
Running the Package

What GPU / hardware type are you using?
Nvidia 3080TI

### Additional information

1

**Comment by JavadZohani** [comment]
These warnings have been completely resolved in Forge, but I don't know why there are no updates to fix these warnings in this program. This problem can be resolved by changing a few codes.

**Comment by Panchovix** [comment]
Solved

**Comment by AnttiHuovilainen** [comment]
I think this might be related - at least it's directly to do with importing timm.layers.

When trying to use any of the segmentation preprocessors, I now get ModuleNotFoundError: No module named 'timm.layers'. 
This happens both on my local machine as well as a four day old fresh cloud install.

I checked and both installs have timm version 0.6.7. Might it be that that needs to be updated if it only exports the old name?

*** Arguments: ('task(wgc2mwlfjp5fmmh)', 0.0, <PIL.Image.Image image mode=RGBA size=1216x832 at 0x218F9B4DA80>, None, '', '', True, False, 0.0, 4, 0.0, 512, 512, True, 'None', 'None', 0, False, 1, False, 1, 0, False, 0.5, 0.2, False, 0.9, 0.15, 0.5, False, False, 384, 768, 4096, 409600, 'Maximize area', 0.1, False, ['Horizontal'], False, ['Deepbooru'], True, 'seg_ufade20k', True, 512, 0.5, 0.5, False, 'None', False, False, 240, 10, 10) {}
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\forge_legacy_preprocessors\annotator\mmpkg\mmcv\utils\misc.py", line 73, in import_modules_from_strings
        imported_tmp = import_module(imp)
      File "importlib\__init__.py", line 126, in import_module
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\forge_legacy_preprocessors\annotator\uniformer\uniformer.py", line 16, in <module>
        from timm.layers import DropPath, to_2tuple, trunc_normal_
    ModuleNotFoundError: No module named 'timm.layers'

    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "D:\webui_forge_cu121_torch21\webui\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
      File "D:\webui_forge_cu121_torch21\webui\modules\call_queue.py", line 53, in f
        res = func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\modules\postprocessing.py", line 133, in run_postprocessing_webui
        return run_postprocessing(*args, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\modules\postprocessing.py", line 73, in run_postprocessing
        scripts.scripts_postproc.run(initial_pp, args)
      File "D:\webui_forge_cu121_torch21\webui\modules\scripts_postprocessing.py", line 221, in run
        script.process(single_image, **process_args)
      File "D:\webui_forge_cu121_torch21\webui\extensions\sd-webui-cn-in-extras-tab\scripts\cn_in_extras_tab.py", line 238, in process
        detected_map = module(
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\forge_legacy_preprocessors\scripts\legacy_preprocessors.py", line 103, in __call__
        result, is_image = self.call_function(img=input_image, res=resolution, thr_a=slider_1, thr_b=slider_2, **kwargs)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\forge_legacy_preprocessors\legacy_preprocessors\preprocessor.py", line 337, in uniformer
        result = model_uniformer(img)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\forge_legacy_preprocessors\annotator\uniformer\__init__.py", line 33, in apply_uniformer
        model = init_segmentor(config_file, modelpath, device=devices.get_device_for("controlnet"))
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\forge_legacy_preprocessors\annotator\uniformer\inference.py", line 31, in init_segmentor
        config = mmcv.Config.fromfile(config)
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\forge_legacy_preprocessors\annotator\mmpkg\mmcv\utils\config.py", line 334, in fromfile
        import_modules_from_strings(**cfg_dict['custom_imports'])
      File "D:\webui_forge_cu121_torch21\webui\extensions-builtin\forge_legacy_preprocessors\annotator\mmpkg\mmcv\utils\misc.py", line 80, in import_modules_from_strings
        raise ImportError
    ImportError

**Comment by Panchovix** [comment]
Okay I just noticed that I didn't add the timm version requirement for some reason. Should be fixed now (added 1.0.14 to the reqs).
