### ISSUE TITLE
[Bug]: Failed to install, no torch==2.3.1 found

### ISSUE THREAD

**Issue by vidu3k333** [Panchovix/stable-diffusion-webui-reForge#213]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

unable to install due to torch. installing a1111 afterward worked fine but installing forge again results in the same problem

### Steps to reproduce the problem

1. locate to `E:\` and pasted `git clone https://github.com/Panchovix/stable-diffusion-webui-reForge.git
cd stable-diffusion-webui-reForge
git checkout main`
2. open `webui-user.bat`

### What should have happened?

I tried installing A1111, it installed torch and launched fine. when I tried installing following the "You have A1111 and you know Git" guide the torch error still appear

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

there are no sysinfo as the webui failed to install

### Console logs

```Shell
7.4.6
PS C:\Users\Admin> cd e:\
PS E:\> git clone https://github.com/Panchovix/stable-diffusion-webui-reForge.git
Cloning into 'stable-diffusion-webui-reForge'...
remote: Enumerating objects: 45932, done.
remote: Counting objects: 100% (10084/10084), done.
remote: Compressing objects: 100% (569/569), done.
remote: Total 45932 (delta 9577), reused 9533 (delta 9515), pack-reused 35848 (from 3)
Receiving objects: 100% (45932/45932), 99.50 MiB | 14.87 MiB/s, done.
Resolving deltas: 100% (32071/32071), done.
PS E:\> cd stable-diffusion-webui-reForge
PS E:\stable-diffusion-webui-reForge> git checkout main
Already on 'main'
Your branch is up to date with 'origin/main'.
PS E:\stable-diffusion-webui-reForge> E:\stable-diffusion-webui-reForge\webui-user.bat
Creating venv in directory E:\stable-diffusion-webui-reForge\venv using python "C:\Users\Admin\AppData\Local\Programs\Python\Python310-32\python.exe"
Requirement already satisfied: pip in e:\stable-diffusion-webui-reforge\venv\lib\site-packages (22.2.1)
Collecting pip
  Using cached pip-24.3.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.2.1
    Uninstalling pip-22.2.1:
      Successfully uninstalled pip-22.2.1
Successfully installed pip-24.3.1
venv "E:\stable-diffusion-webui-reForge\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:38:17) [MSC v.1932 32 bit (Intel)]
Version: f1.1.5-v1.10.1RC-latest-866-g82c17c39
Commit hash: 82c17c39e0a1aff991f897290d857a57a778b9ec
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
ERROR: Could not find a version that satisfies the requirement torch==2.3.1 (from versions: none)
ERROR: No matching distribution found for torch==2.3.1
Traceback (most recent call last):
  File "E:\stable-diffusion-webui-reForge\launch.py", line 51, in <module>
    main()
  File "E:\stable-diffusion-webui-reForge\launch.py", line 39, in main
    prepare_environment()
  File "E:\stable-diffusion-webui-reForge\modules\launch_utils.py", line 426, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "E:\stable-diffusion-webui-reForge\modules\launch_utils.py", line 125, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install torch.
Command: "E:\stable-diffusion-webui-reForge\venv\Scripts\python.exe" -m pip install torch==2.3.1 torchvision==0.18.1 --extra-index-url https://download.pytorch.org/whl/cu121
Error code: 1
Press any key to continue . . .
```

**Comment by Panchovix** [comment]
Hi there, thanks. It seems torch 2.3.1 got taken out of torch page. 

Pushed a commit that should have updated torch and fix this. After updating, let me know if the issue persists.

**Comment by JohnCale47** [comment]
bump.. updated repo also has this problem
```

Python 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)]
Version: f1.1.5-v1.10.1RC-latest-876-g62d901b3
Commit hash: 62d901b37e47d273d05532620a4bc33eddc2de08
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu124
ERROR: Could not find a version that satisfies the requirement torch==2.5.1 (from versions: none)
ERROR: No matching distribution found for torch==2.5.1
Traceback (most recent call last):
  File "C:\Softwares\stable-diffusion-webui-reForge\launch.py", line 51, in <module>
    main()
    ~~~~^^
  File "C:\Softwares\stable-diffusion-webui-reForge\launch.py", line 39, in main
    prepare_environment()
    ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Softwares\stable-diffusion-webui-reForge\modules\launch_utils.py", line 424, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Softwares\stable-diffusion-webui-reForge\modules\launch_utils.py", line 123, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install torch.
Command: "C:\Softwares\stable-diffusion-webui-reForge\venv\Scripts\python.exe" -m pip install torch==2.5.1 torchvision==0.20.1 --extra-index-url https://download.pytorch.org/whl/cu124
Error code: 1
```
