### ISSUE TITLE
[Bug]: MSW-MSA error even when not using it.

### ISSUE THREAD

**Issue by acorderob** [Panchovix/stable-diffusion-webui-reForge#221]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Exception when using resolutions not multiple of 64 (like 4K in hiresfix), but MSW-MSA is not active. It worked before MSW-MSA was added, and the extension should not even be used.

### Steps to reproduce the problem

1. Choose a resolution not multiple of 64, for example 1024x560.
2. Have "RAUNet/MSW-MSA for reForge" **not active** in any tab.
3. Generate.
4. Error!

### What should have happened?

Should have generated.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-12-28-13-55.json](https://github.com/user-attachments/files/18266379/sysinfo-2024-12-28-13-55.json)

### Console logs

```Shell
Traceback (most recent call last):
  File "D:\Other Applications\stable-diffusion-webui-reForge\extensions-builtin\reforge_jankhidiffusion\HiDiffusion\msw_msa_attention.py", line 145, in attn1_patch
    self.window_partition(
  File "D:\Other Applications\stable-diffusion-webui-reForge\extensions-builtin\reforge_jankhidiffusion\HiDiffusion\msw_msa_attention.py", line 40, in window_partition
    x = x.view(
RuntimeError: shape '[2, 2, 17, 2, 32, 640]' is invalid for input of size 2867200

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Other Applications\stable-diffusion-webui-reForge\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "D:\Other Applications\stable-diffusion-webui-reForge\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\Other Applications\stable-diffusion-webui-reForge\modules\txt2img.py", line 114, in txt2img_function
    processed = processing.process_images(p)
  File "D:\Other Applications\stable-diffusion-webui-reForge\modules\processing.py", line 823, in process_images
    res = process_images_inner(p)
  File "D:\Other Applications\stable-diffusion-webui-reForge\modules\processing.py", line 981, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\Other Applications\stable-diffusion-webui-reForge\modules\processing.py", line 1356, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\Other Applications\stable-diffusion-webui-reForge\modules\sd_samplers_kdiffusion.py", line 295, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\Other Applications\stable-diffusion-webui-reForge\modules\sd_samplers_common.py", line 280, in launch_sampling
    return func()
  File "D:\Other Applications\stable-diffusion-webui-reForge\modules\sd_samplers_kdiffusion.py", line 295, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\Other Applications\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Other Applications\stable-diffusion-webui-reForge\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\Other Applications\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Other Applications\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Other Applications\stable-diffusion-webui-reForge\modules\sd_samplers_cfg_denoiser.py", line 228, in forward
    denoised = sampling_function(model, x, sigma, uncond_patched, cond_patched, cond_scale, model_options, seed)
  File "D:\Other Applications\stable-diffusion-webui-reForge\ldm_patched\modules\samplers.py", line 295, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "D:\Other Applications\stable-diffusion-webui-reForge\ldm_patched\modules\samplers.py", line 258, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "D:\Other Applications\stable-diffusion-webui-reForge\ldm_patched\modules\model_base.py", line 90, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "D:\Other Applications\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Other Applications\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Other Applications\stable-diffusion-webui-reForge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 886, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "D:\Other Applications\stable-diffusion-webui-reForge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 55, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "D:\Other Applications\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Other Applications\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Other Applications\stable-diffusion-webui-reForge\ldm_patched\ldm\modules\attention.py", line 617, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "D:\Other Applications\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Other Applications\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Other Applications\stable-diffusion-webui-reForge\ldm_patched\ldm\modules\attention.py", line 444, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "D:\Other Applications\stable-diffusion-webui-reForge\ldm_patched\ldm\modules\diffusionmodules\util.py", line 194, in checkpoint
    return func(*inputs)
  File "D:\Other Applications\stable-diffusion-webui-reForge\ldm_patched\ldm\modules\attention.py", line 483, in _forward
    n, context_attn1, value_attn1 = p(n, context_attn1, value_attn1, extra_options)
  File "D:\Other Applications\stable-diffusion-webui-reForge\extensions-builtin\reforge_jankhidiffusion\HiDiffusion\msw_msa_attention.py", line 158, in attn1_patch
    raise RuntimeError(errstr) from exc
RuntimeError: MSW-MSA attention error: Incompatible model patches or bad resolution. Try using resolutions that are multiples of 32 or 64. Original exception: shape '[2, 2, 17, 2, 32, 640]' is invalid for input of size 2867200
MSW-MSA attention error: Incompatible model patches or bad resolution. Try using resolutions that are multiples of 32 or 64. Original exception: shape '[2, 2, 17, 2, 32, 640]' is invalid for input of size 2867200
```

### Additional information

With the extension disabled it works.

**Comment by Panchovix** [comment]
Thanks, moved the extension out as built in as separate to fix this in the meanwhile.

It can be found on: https://github.com/Panchovix/reforge_jankhidiffusion.git
