### ISSUE TITLE
[Bug]: ControlNet TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by prog-ape** [Panchovix/stable-diffusion-webui-reForge#23]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Using ControlNet's OpenPose and Inpaint in img2img

### Steps to reproduce the problem

Using ControlNet's OpenPose and Inpaint in img2img

### What should have happened?

Normal output

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

See follow up posts

### Console logs

```Shell
2024-07-16 02:18:35,085 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-07-16 02:18:35,126 - ControlNet - INFO - Using preprocessor: dw_openpose_full
2024-07-16 02:18:35,126 - ControlNet - INFO - preprocessor resolution = 1024
Automatic Memory Management: 0 Modules in 0.00 seconds.
2024-07-16 02:18:36,289 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\stable-diffusion-webui-reForge\models\ControlNet\control_v11p_sd15_openpose.pth
2024-07-16 02:18:36,289 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-07-16 02:18:36,331 - ControlNet - INFO - Using preprocessor: inpaint_only
2024-07-16 02:18:36,331 - ControlNet - INFO - preprocessor resolution = 1024
2024-07-16 02:18:36,342 - ControlNet - INFO - Current ControlNet ControlNetPatcher: D:\stable-diffusion-webui-reForge\models\ControlNet\control_v11p_sd15_inpaint.pth
2024-07-16 02:18:36,522 - ControlNet - INFO - ControlNet Method dw_openpose_full patched.
*** Error running process_before_every_sampling: D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-reForge\modules\scripts.py", line 885, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\anaconda3\envs\forge\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 574, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
      File "D:\anaconda3\envs\forge\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 511, in process_unit_before_every_sampling
        cond, mask = params.preprocessor.process_before_every_sampling(p, cond, mask, *args, **kwargs)
      File "D:\stable-diffusion-webui-reForge\extensions-builtin\forge_preprocessor_inpaint\scripts\preprocessor_inpaint.py", line 41, in process_before_every_sampling
        mask = mask.round()
    AttributeError: 'NoneType' object has no attribute 'round'

---
2024-07-16 02:18:36,528 - ControlNet - INFO - ControlNet Method dw_openpose_full patched.
*** Error running process_before_every_sampling: D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-reForge\modules\scripts.py", line 885, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\anaconda3\envs\forge\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 574, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
      File "D:\anaconda3\envs\forge\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 511, in process_unit_before_every_sampling
        cond, mask = params.preprocessor.process_before_every_sampling(p, cond, mask, *args, **kwargs)
      File "D:\stable-diffusion-webui-reForge\extensions-builtin\forge_preprocessor_inpaint\scripts\preprocessor_inpaint.py", line 41, in process_before_every_sampling
        mask = mask.round()
    AttributeError: 'NoneType' object has no attribute 'round'

---
To load target model BaseModel
To load target model ControlNet
Begin to load 2 models
Reuse 1 loaded models
Reuse 1 loaded models
[Memory Management] Current Free GPU Memory (MB) =  20018.000032424927
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  18994.000032424927
[Memory Management] Current Free GPU Memory (MB) =  20018.000032424927
[Memory Management] Model Memory (MB) =  0.0
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  18994.000032424927
Moving model(s) has taken 0.01 seconds
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.98it/s]
*** Error running postprocess_batch_list: D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-reForge\modules\scripts.py", line 909, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\anaconda3\envs\forge\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 580, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
      File "D:\anaconda3\envs\forge\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 555, in process_unit_after_every_sampling
        params.preprocessor.process_after_every_sampling(p, params, *args, **kwargs)
      File "D:\stable-diffusion-webui-reForge\extensions-builtin\forge_preprocessor_inpaint\scripts\preprocessor_inpaint.py", line 86, in process_after_every_sampling
        mask = self.mask[0, 0].detach().cpu().numpy().astype(np.float32)
    TypeError: 'NoneType' object is not subscriptable

---
```

**Comment by Panchovix** [comment]
Thanks for the report. Are you on main or dev_upstream branch?

**Comment by prog-ape** [comment]
> Thanks for the report. Are you on main or dev_upstream branch? Does this feature work on original forge?

It is on the main branch and has not been tested on the original forge version.

**Comment by prog-ape** [comment]
After switching to dev_upstream and executing the commands, there are still exceptions

2024-07-16 11:30:46,855 - ControlNet - INFO - ControlNet Input Mode: InputMode.SIMPLE
2024-07-16 11:30:46,901 - ControlNet - INFO - Using preprocessor: dw_openpose_full
2024-07-16 11:30:46,901 - ControlNet - INFO - preprocessor resolution = 1024
Automatic Memory Management: 0 Modules in 0.00 seconds.
WARNING:root:Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
*** Error running process: D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-reForge\modules\scripts.py", line 845, in process
        script.process(p, *script_args)
      File "D:\anaconda3\envs\forge\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 567, in process
        self.process_unit_after_click_generate(p, unit, params, *args, **kwargs)
      File "D:\anaconda3\envs\forge\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 420, in process_unit_after_click_generate
        params.model = cached_controlnet_loader(model_filename)
      File "D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 52, in cached_controlnet_loader
        return try_load_supported_control_model(filename)
      File "D:\stable-diffusion-webui-reForge\modules_forge\shared.py", line 63, in try_load_supported_control_model
        model = supported_type.try_build_from_state_dict(state_dict_copy, ckpt_path)
      File "D:\stable-diffusion-webui-reForge\modules_forge\supported_controlnet.py", line 108, in try_build_from_state_dict
        controlnet_config = ldm_patched.modules.model_detection.model_config_from_unet(controlnet_data, prefix,
    TypeError: model_config_from_unet() takes from 2 to 3 positional arguments but 4 were given

---
*** Error running process_before_every_sampling: D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-reForge\modules\scripts.py", line 885, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\anaconda3\envs\forge\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 574, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
*** Error running process_before_every_sampling: D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-reForge\modules\scripts.py", line 885, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\anaconda3\envs\forge\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 574, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

---
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  6.75it/s]
*** Error running postprocess_batch_list: D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-reForge\modules\scripts.py", line 909, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\anaconda3\envs\forge\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 580, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0

---

**Comment by Panchovix** [comment]
> > Thanks for the report. Are you on main or dev_upstream branch? Does this feature work on original forge?
> 
> It is on the main branch and has not been tested on the original forge version.

Can you try this commit

`git checkout bfee03d`

And see if this works? This is to see if it's an issue from forge itself or the updates.

**Comment by prog-ape** [comment]
> > > Thanks for the report. Are you on main or dev_upstream branch? Does this feature work on original forge?
> > 
> > 
> > It is on the main branch and has not been tested on the original forge version.
> 
> Can you try this commit
> 
> `git checkout bfee03d`
> 
> And see if this works? This is to see if it's an issue from forge itself or the updates.

git checkout bfee03d works fine. Another issue is that the execution speed of main and dev_upstream is significantly slower than the original version of Forge. It feels like the execution speed of the original WebUI.

**Comment by Panchovix** [comment]
> > > > Thanks for the report. Are you on main or dev_upstream branch? Does this feature work on original forge?
> > > 
> > > 
> > > It is on the main branch and has not been tested on the original forge version.
> > 
> > 
> > Can you try this commit
> > `git checkout bfee03d`
> > And see if this works? This is to see if it's an issue from forge itself or the updates.
> 
> git checkout [bfee03d](https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/bfee03d8d9415a925616f40ede030fe7a51cbcfd) works fine. Another issue is that the execution speed of main and dev_upstream is significantly slower than the original version of Forge. It feels like the execution speed of the original WebUI.

Okay, so it is because a change.

About the speeds, at least the main branch should perform exactly as original forge (except on img2img), since there is no backend modifications. dev_upstream has a lot of modifications so that's possible.

If you notice a difference in img2img, it's because it is using the A1111 backend on main instead of the comfy one, since it gave some issues.

Gonna check anyways, thanks for the report.

**Comment by prog-ape** [comment]
> > > > > Thanks for the report. Are you on main or dev_upstream branch? Does this feature work on original forge?
> > > > 
> > > > 
> > > > It is on the main branch and has not been tested on the original forge version.
> > > 
> > > 
> > > Can you try this commit
> > > `git checkout bfee03d`
> > > And see if this works? This is to see if it's an issue from forge itself or the updates.
> > 
> > 
> > git checkout [bfee03d](https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/bfee03d8d9415a925616f40ede030fe7a51cbcfd) works fine. Another issue is that the execution speed of main and dev_upstream is significantly slower than the original version of Forge. It feels like the execution speed of the original WebUI.
> 
> Okay, so it is because a change.
> 
> About the speeds, at least the main branch should perform exactly as original forge (except on img2img), since there is no backend modifications. dev_upstream has a lot of modifications so that's possible.
> 
> If you notice a difference in img2img, it's because it is using the A1111 backend on main instead of the comfy one, since it gave some issues.
> 
> Gonna check anyways, thanks for the report.

Thank you for your work. If the execution speed could match that of Forge, it would be perfect.

**Comment by Panchovix** [comment]
I have returned to main thread (like original forge) on main and dev_upstream, that should help with the performance.

Not sure about controlnet, you can test if you want to check.

**Comment by prog-ape** [comment]
still the same error

**Comment by Panchovix** [comment]
Thanks for the confirmation. I'm gonna check when I can why that is happening. I did have some controlnet reversions since it was giving another issues. Maybe gonna create a branch without that reversions and see if it work.

**Comment by Panchovix** [comment]
I did an experimental commit on dev_upstream

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/6b8d3081c964e22fee73aeb54c6451a68a0887db

Can you try if you still get the issue?

**Comment by Panchovix** [comment]
> Thank you for this, I was having the same error message but not in ControlNet, rather in doing any regular gen. I did git checkout [e6ef03c](https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/e6ef03cb6b6af94b5c81c21a634315a19002044a) and seemingly fixed the issue, with I think a reasonable speed (RTX 4090, 15.8 second gen time on 1216x832 upscaled 1.5x to 1824x1248 in Hiresfix)

Nice! If using dev_upstream you can update to latest commit without issues as well.

**Comment by Reithan** [comment]
I'm having this issue right now when trying to use controlNet inpaint on Img2Img. It seems like it doesn't allow for any workflow that utilized ControlNet Inpaint without a mask.

**Comment by Reithan** [comment]
This is also breaking and throwing this error periodically even when a mask is set. Sometimes using the 'variant' versions helps, sometimes not.
