### ISSUE TITLE
dev_upstream IPadapter  issue[Bug]: 

### ISSUE THREAD

**Issue by githabtane** [Panchovix/stable-diffusion-webui-reForge#25]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

 TypeError: CLIPVision.forward() got an unexpected keyword argument 'output_hidden_states'

### Steps to reproduce the problem

1

### What should have happened?

 TypeError: CLIPVision.forward() got an unexpected keyword argument 'output_hidden_states'

### Sysinfo

1

### Console logs

```Shell
*** Error running process_before_every_sampling: D:\ReForge2\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\ReForge2\stable-diffusion-webui-reForge\modules\scripts.py", line 885, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 574, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 518, in process_unit_before_every_sampling
        params.model.process_before_every_sampling(p, cond, mask, *args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_ipadapter\scripts\forge_ipadapter.py", line 147, in process_before_every_sampling
        unet = opIPAdapterApply(
      File "D:\ReForge2\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_ipadapter\lib_ipadapter\IPAdapterPlus.py", line 722, in apply_ipadapter
        clip_embed_zeroed = zeroed_hidden_states(clip_vision, image.shape[0])
      File "D:\ReForge2\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_ipadapter\lib_ipadapter\IPAdapterPlus.py", line 196, in zeroed_hidden_states
        outputs = clip_vision.model(pixel_values=pixel_values, output_hidden_states=True)
      File "D:\ReForge2\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\ldm_patched\modules\clip_model.py", line 196, in forward
        x = self.vision_model(*args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
    TypeError: CLIPVision.forward() got an unexpected keyword argument 'output_hidden_states'

---
*** Error running process_before_every_sampling: D:\ReForge2\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\ReForge2\stable-diffusion-webui-reForge\modules\scripts.py", line 885, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 574, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 518, in process_unit_before_every_sampling
        params.model.process_before_every_sampling(p, cond, mask, *args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_ipadapter\scripts\forge_ipadapter.py", line 147, in process_before_every_sampling
        unet = opIPAdapterApply(
      File "D:\ReForge2\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_ipadapter\lib_ipadapter\IPAdapterPlus.py", line 722, in apply_ipadapter
        clip_embed_zeroed = zeroed_hidden_states(clip_vision, image.shape[0])
      File "D:\ReForge2\stable-diffusion-webui-reForge\extensions-builtin\sd_forge_ipadapter\lib_ipadapter\IPAdapterPlus.py", line 196, in zeroed_hidden_states
        outputs = clip_vision.model(pixel_values=pixel_values, output_hidden_states=True)
      File "D:\ReForge2\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\ldm_patched\modules\clip_model.py", line 196, in forward
        x = self.vision_model(*args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
    TypeError: CLIPVision.forward() got an unexpected keyword argument 'output_hidden_states'
```

**Comment by Panchovix** [comment]
Thanks for the report.

I did update clip vision yesterday to comfy upstream, but maybe it has some issues.

If you go to an older commits, does it work fine?

`git commit ed76bea`

**Comment by Panchovix** [comment]
Okay I've pushed a commit that should fix this

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/2779a85c198f827bf58aa88b4cf83191d22f08ed

Can you try and see how it goes, or if it gives another issue?

**Comment by githabtane** [comment]
thank you. There seems to be no problem
