### ISSUE TITLE
Layerdiffuse

### ISSUE THREAD

**Issue by githabtane** [Panchovix/stable-diffusion-webui-reForge#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

The extension "LayerDiffuse" works on the "main" branch, but an error occurs on the "dev_upstream" branch. Is there any solution? I don't understand English, so I'm sorry that I can't explain it well.

### Proposed workflow

1

### Additional information

1

**Comment by Panchovix** [comment]
I have fixed it on last commit, thanks for the report.

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/eea0d9b9d791bdbbef8a7bd0d82d4b1e349ecb7b

**Comment by githabtane** [comment]
Traceback (most recent call last):
      File "D:\Forge\stable-diffusion-webui-reForge\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

**Comment by Panchovix** [comment]
Now it should be fixed after https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/f607c9a24219978ed6499ff125eb9eb9d4adf1f6

VAE clone was missing come values

**Comment by githabtane** [comment]
---
[Layer Diffusion] LayerMethod.FG_ONLY_ATTN_SD15
*** Error running process_before_every_sampling: D:\ReForge2\stable-diffusion-webui-reForge\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py
    Traceback (most recent call last):
      File "D:\ReForge2\stable-diffusion-webui-reForge\modules\scripts.py", line 885, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\ReForge2\stable-diffusion-webui-reForge\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 226, in process_before_every_sampling
        patcher = AttentionSharingPatcher(unet, frames=1, use_control=False)
      File "D:\ReForge2\stable-diffusion-webui-reForge\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\attention_sharing.py", line 208, in __init__
        attn_module = utils.get_attr(unet.model.diffusion_model, real_key)
      File "D:\ReForge2\stable-diffusion-webui-reForge\ldm_patched\modules\utils.py", line 397, in get_attr
        obj = getattr(obj, name)
      File "D:\ReForge2\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
    AttributeError: 'TimestepEmbedSequential' object has no attribute '1'

**Comment by githabtane** [comment]
![スクリーンショット 2024-07-17 192737](https://github.com/user-attachments/assets/7351157f-562f-4b09-aaa7-08d606ea3d5d)

**Comment by githabtane** [comment]
main branch
![スクリーンショット 2024-07-17 193437](https://github.com/user-attachments/assets/4bed4f63-24d4-4a98-aefc-f592914b8b79)

**Comment by githabtane** [comment]
python 3.10.11 NVIDIA GeForce RTX 4060 Ti  16GB
controlnet softedge  error
pip install basicsr<< works fine
Is there a problem with "requirements.txt"?
I'm an amateur so I don't really understand.

**Comment by Panchovix** [comment]
Sos did you install basicsr and it worked fine?

Maybe requirements.txt could have that but it should a req of layer diffusion when installing it
