### ISSUE TITLE
IC Light not working on dev upstream

### ISSUE THREAD

**Issue by Newtrial99** [Panchovix/stable-diffusion-webui-reForge#30]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

So I tried using the IC light extension for forge ui by huchenlei, but it returns the error.  AttributeError: 'VAE' object has no attribute 'process_input'

Hence the IC light input is completely ignored.

### Steps to reproduce the problem

using Forge IC light extension by huchenlei

### What should have happened?

.

### Sysinfo

.

### Console logs

```Shell
Error running process_before_every_sampling: E:\refor\stable-diffusion-webui-reForge\extensions\sd-forge-ic-light\scripts\ic_light_script.py
    Traceback (most recent call last):
      File "E:\refor\stable-diffusion-webui-reForge\modules\scripts.py", line 885, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "E:\refor\stable-diffusion-webui-reForge\extensions\sd-forge-ic-light\scripts\ic_light_script.py", line 277, in process_before_every_sampling
        self.apply_ic_light(p, self.args)
      File "E:\refor\stable-diffusion-webui-reForge\extensions\sd-forge-ic-light\libiclight\forge_backend.py", line 44, in apply_ic_light
        c_concat={"samples": vae.encode(pixel_concat)},
      File "E:\refor\stable-diffusion-webui-reForge\ldm_patched\modules\sd.py", line 382, in encode
        pixels_in = self.process_input(pixel_samples[x:x+batch_number]).to(self.vae_dtype).to(self.device)
    AttributeError: 'VAE' object has no attribute 'process_input'
```

**Comment by Panchovix** [comment]
Hi, thanks for the report.

You're correct.

Pushed a new commit that should fix it

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/99cb084fbdac6e0084052b82bbe31140867b9213

Can you try and see how it goes?

**Comment by Newtrial99** [comment]
> Hi, thanks for the report.
> 
> You're correct.
> 
> Pushed a new commit that should fix it
> 
> [99cb084](https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/99cb084fbdac6e0084052b82bbe31140867b9213)
> 
> Can you try and see how it goes?
> 
> EDIT: Tried and no more VAE issue, but got another issue maybe related to conv2d or ldm\modules\diffusionmodules\openaimodel.py (I did some updates for those 2 recently and maybe that's why).
> 
> But also I don't know how to use the extension haha



tried it, the vae problem was fixed, now I got another problem, its probably a mistake from my end, I will re download the Ic light model and try again thanks. 

the current problem, (most likely from my end).

Traceback (most recent call last):
  File "E:\refor\stable-diffusion-webui-reForge\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "E:\refor\stable-diffusion-webui-reForge\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "E:\refor\stable-diffusion-webui-reForge\modules\img2img.py", line 235, in img2img_function
    processed = process_images(p)
  File "E:\refor\stable-diffusion-webui-reForge\modules\processing.py", line 815, in process_images
    res = process_images_inner(p)
  File "E:\refor\stable-diffusion-webui-reForge\modules\processing.py", line 988, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "E:\refor\stable-diffusion-webui-reForge\modules\processing.py", line 1816, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "E:\refor\stable-diffusion-webui-reForge\modules\sd_samplers_kdiffusion.py", line 182, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "E:\refor\stable-diffusion-webui-reForge\modules\sd_samplers_common.py", line 274, in launch_sampling
    return func()
  File "E:\refor\stable-diffusion-webui-reForge\modules\sd_samplers_kdiffusion.py", line 182, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "E:\refor\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\refor\stable-diffusion-webui-reForge\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "E:\refor\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\refor\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\refor\stable-diffusion-webui-reForge\modules\sd_samplers_cfg_denoiser.py", line 369, in forward
    denoised = sampling_function(model, x, sigma, uncond_patched, cond_patched, cond_scale, model_options, seed)
  File "E:\refor\stable-diffusion-webui-reForge\ldm_patched\modules\samplers.py", line 290, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "E:\refor\stable-diffusion-webui-reForge\ldm_patched\modules\samplers.py", line 257, in calc_cond_uncond_batch
    output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
  File "E:\refor\stable-diffusion-webui-reForge\extensions\sd-forge-ic-light\libiclight\ic_light_nodes.py", line 61, in wrapper_func
    return existing_wrapper(unet_apply, params=apply_c_concat(params))
  File "E:\refor\stable-diffusion-webui-reForge\extensions\sd-forge-ic-light\libiclight\ic_light_nodes.py", line 53, in unet_dummy_apply
    return unet_apply(x=params["input"], t=params["timestep"], **params["c"])
  File "E:\refor\stable-diffusion-webui-reForge\ldm_patched\modules\model_base.py", line 118, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "E:\refor\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\refor\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\refor\stable-diffusion-webui-reForge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 859, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "E:\refor\stable-diffusion-webui-reForge\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 57, in forward_timestep_embed
    x = layer(x)
  File "E:\refor\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\refor\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\refor\stable-diffusion-webui-reForge\ldm_patched\modules\ops.py", line 135, in forward
    return self.forward_ldm_patched_cast_weights(*args, **kwargs)
  File "E:\refor\stable-diffusion-webui-reForge\ldm_patched\modules\ops.py", line 131, in forward_ldm_patched_cast_weights
    return self._conv_forward(input, weight, bias)
  File "E:\refor\stable-diffusion-webui-reForge\venv\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[1, 8, 96, 144] to have 4 channels, but got 8 channels instead
Given groups=1, weight of size [320, 4, 3, 3], expected input[1, 8, 96, 144] to have 4 channels, but got 8 channels instead
*** Error completing request

…………

Traceback (most recent call last):
      File "E:\refor\stable-diffusion-webui-reForge\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

**Comment by Panchovix** [comment]
Don't worry, I get the same issue. I changed the code on https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/2fd939db699748b8080536c09c00cc04c141bd4a and https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/53f431665fee3e68cf868ae92d7848a8a6b73c67 commits, so probably a change from there is not adapted yet in the extension (it seems it uses the forge while dev_upstream has the comfy updates)

**Comment by Panchovix** [comment]
I have opened a issue on the extension repo asking for reforge support https://github.com/huchenlei/sd-forge-ic-light/issues/36

Hope we can reach something!
