### ISSUE TITLE
[Bug]: Can't load dev_upstream with default settings

### ISSUE THREAD

**Issue by itsagoodbrain** [Panchovix/stable-diffusion-webui-reForge#59]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Tried to run the dev_upscale branch and got an error with the default attention implementation (for AMD).

### Steps to reproduce the problem

1. Install reForge
2. Run with main branch (success)
3. Switch to dev_upstream branch (fail)
4. Run with --attention-pytorch option (success)

### What should have happened?

Loaded webui

### What browsers do you use to access the UI ?

Google Chrome, Brave

### Sysinfo

[sysinfo.json](https://github.com/user-attachments/files/16354049/sysinfo.json)

### Console logs

```Shell
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
Version: f0.0.20.1dev-v1.10.0RC-latest-761-g4fe9b0eb
Commit hash: 4fe9b0eb9517f439fa4e648398f9b876bb911dce
CUDA None
Launching Web UI with arguments:
amdgpu.ids: No such file or directory
Total VRAM 12272 MB, total RAM 32012 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon Graphics : native
VAE dtype: torch.float32
CUDA Stream Activated:  False
Traceback (most recent call last):
  File "/home/user/MyCode/stable-diffusion/reForge/launch.py", line 51, in <module>
    main()
  File "/home/user/MyCode/stable-diffusion/reForge/launch.py", line 47, in main
    start()
  File "/home/user/MyCode/stable-diffusion/reForge/modules/launch_utils.py", line 542, in start
    import webui
  File "/home/user/MyCode/stable-diffusion/reForge/webui.py", line 19, in <module>
    initialize.imports()
  File "/home/user/MyCode/stable-diffusion/reForge/modules/initialize.py", line 53, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "/home/user/MyCode/stable-diffusion/reForge/modules/processing.py", line 18, in <module>
    import modules.sd_hijack
  File "/home/user/MyCode/stable-diffusion/reForge/modules/sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "/home/user/MyCode/stable-diffusion/reForge/modules/sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "/home/user/MyCode/stable-diffusion/reForge/modules/hypernetworks/hypernetwork.py", line 8, in <module>
    import modules.textual_inversion.dataset
  File "/home/user/MyCode/stable-diffusion/reForge/modules/textual_inversion/dataset.py", line 12, in <module>
    from modules import devices, shared, images
  File "/home/user/MyCode/stable-diffusion/reForge/modules/images.py", line 25, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors
  File "/home/user/MyCode/stable-diffusion/reForge/modules/sd_samplers.py", line 5, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared, sd_samplers_common, sd_schedulers
  File "/home/user/MyCode/stable-diffusion/reForge/modules/sd_samplers_kdiffusion.py", line 4, in <module>
    from modules import sd_samplers_common, sd_samplers_extra, sd_samplers_cfg_denoiser, sd_schedulers
  File "/home/user/MyCode/stable-diffusion/reForge/modules/sd_samplers_common.py", line 6, in <module>
    from modules import devices, images, sd_vae_approx, sd_samplers, sd_vae_taesd, shared, sd_models
  File "/home/user/MyCode/stable-diffusion/reForge/modules/sd_models.py", line 19, in <module>
    from modules_forge import forge_loader
  File "/home/user/MyCode/stable-diffusion/reForge/modules_forge/forge_loader.py", line 5, in <module>
    from ldm_patched.modules import model_detection
  File "/home/user/MyCode/stable-diffusion/reForge/ldm_patched/modules/model_detection.py", line 5, in <module>
    import ldm_patched.modules.supported_models
  File "/home/user/MyCode/stable-diffusion/reForge/ldm_patched/modules/supported_models.py", line 5, in <module>
    from . import model_base
  File "/home/user/MyCode/stable-diffusion/reForge/ldm_patched/modules/model_base.py", line 6, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "/home/user/MyCode/stable-diffusion/reForge/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 23, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/home/user/MyCode/stable-diffusion/reForge/ldm_patched/ldm/modules/attention.py", line 454, in <module>
    if args.use_split_cross_attention:
AttributeError: 'Namespace' object has no attribute 'use_split_cross_attention'
```

**Comment by itsagoodbrain** [comment]
Wanted to also say thank you for continuing on updating Forge! You're doing great work, hope I can at least contribute by testing and notifying when things break.

**Comment by Panchovix** [comment]
Hi there, so on dev, only when running with default commands and no xformers, you get that issue? I think I found the issue, pushed a possible fix. Can you try and see how it goes?

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/f65dea017a60205c30f50209073e0a2c43eec3e1



> Wanted to also say thank you for continuing on updating Forge! You're doing great work, hope I can at least contribute by testing and notifying when things break.

Thanks!

**Comment by itsagoodbrain** [comment]
Fixed! Thanks!
