### ISSUE TITLE
[Bug]: Smea Dy no longer works after commit 4742976

### ISSUE THREAD

**Issue by aoleg** [Panchovix/stable-diffusion-webui-reForge#62]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

After updating main branch to commit 47429765eaf26c8a55674f27f1a12247de697a80, using "Euler Smea Dy" scheduler is no longer possible. Checked with "Automatic" and "Align Your Steps" schedulers; both failed. Reverting to an earlier commit fixed the issue. Please consider reverting the changes.

### Steps to reproduce the problem

Select Euler SMEA Dy as a sampler.
Select either "Automatic" or "Align Your Steps" as a scheduler.
Start generation.
Generation will fail.

### What should have happened?

Should work normally.

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

Commit 47429765eaf26c8a55674f27f1a12247de697a80

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-reForge\webui\modules_forge\main_thread.py", line 37, in loop
    task.work()
  File "C:\stable-diffusion-webui-reForge\webui\modules_forge\main_thread.py", line 26, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "C:\stable-diffusion-webui-reForge\webui\modules\txt2img.py", line 110, in txt2img_function
    processed = processing.process_images(p)
  File "C:\stable-diffusion-webui-reForge\webui\modules\processing.py", line 815, in process_images
    res = process_images_inner(p)
  File "C:\stable-diffusion-webui-reForge\webui\modules\processing.py", line 988, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "C:\stable-diffusion-webui-reForge\webui\modules\processing.py", line 1362, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\stable-diffusion-webui-reForge\webui\modules\sd_samplers_kdiffusion.py", line 261, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\stable-diffusion-webui-reForge\webui\modules\sd_samplers_common.py", line 274, in launch_sampling
    return func()
  File "C:\stable-diffusion-webui-reForge\webui\modules\sd_samplers_kdiffusion.py", line 261, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\stable-diffusion-webui-reForge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\stable-diffusion-webui-reForge\webui\modules\sd_samplers_kdiffusion_smea.py", line 119, in sample_euler_smea_dy
    s_churn = modules.shared.opts.get('euler_smea_dy_s_churn', s_churn)
  File "C:\stable-diffusion-webui-reForge\webui\modules\options.py", line 142, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'get'
'Options' object has no attribute 'get'
*** Error completing request
*** Arguments: ('task(p1insh9ij05250f)', <gradio.routes.Request object at 0x00000286410D6470>, 'test', '', [], 1, 1, 7, 1024, 1024, False, 0.15, 2, '4xNomos8kSCHAT-L', 15, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', [], 0, 60, 'Euler SMEA Dy', 'Automatic', False, 

<<skipped>>

    Traceback (most recent call last):
      File "C:\stable-diffusion-webui-reForge\webui\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
    TypeError: 'NoneType' object is not iterable

---
```

### Additional information

Updated to commit 47429765eaf26c8a55674f27f1a12247de697a80

**Comment by Panchovix** [comment]
Hi there, thanks for the report. Pushed a commit that fixes this, it was an error on my end.

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/b301407965ea01fb7ffa6deb1d7bbd00deb3d8e6

https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/0ca1b9bdc8072417168a0df1a4156d0ab85a9209

Closing the issue for now.
