### ISSUE TITLE
[Bug]: disable SVD will KeyError

### ISSUE THREAD

**Issue by pinea00** [Panchovix/stable-diffusion-webui-reForge#75]
### Checklist

- [x] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Disabling SVD will cause it to fail to start

### Steps to reproduce the problem

1. Disable SVD
2. Close the UI and re-open it.

### What should have happened?

fail to start

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

Unable to enter UI（delete config.json or delete"disabled_extensions": [        "sd_forge_svd",     )

### Console logs

```Shell
venv "S:\venvzluda\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f0.0.20.1-v1.10.0RC-latest-611-gb4333977
Commit hash: b4333977808de856ec189f31c41245a4597b1ed2
Launching Web UI with arguments: --theme dark --api --autolaunch --skip-install
Total VRAM 8176 MB, total RAM 32606 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 6600 [ZLUDA] : native
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using pytorch cross attention
ControlNet preprocessor location: S:\stable-diffusion-webui\models\ControlNetPreprocessor
watermark logo: S:\stable-diffusion-webui\extensions\sd-webui-facefusion-dev\watermark.png
[-] sd-webui-facefusion initialized. FaceFusion 2.1.2
2024-07-28 00:14:42,208 - AnimateDiff - INFO - AnimateDiff Hooking i2i_batch
Loading model dreamshaperXL_v21TurboDPMSDE.safetensors [4496b36d48] (1 out of 1)
Loading weights [4496b36d48] from S:\stable-diffusion-webui\models\Stable-diffusion\dreamshaperXL_v21TurboDPMSDE.safetensors
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
left over keys: dict_keys(['conditioner.embedders.0.logit_scale', 'conditioner.embedders.0.text_projection'])
To load target model SDXLClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  8008.3046875
[Memory Management] Model Memory (MB) =  2144.3546981811523
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  4839.949989318848
Moving model(s) has taken 0.56 seconds
Model loaded in 11.6s (load weights from disk: 0.5s, forge load real models: 9.8s, calculate empty prompt: 1.3s).
2024-07-28 00:14:54,218 - ControlNet - INFO - ControlNet UI callback registered.
Exception in thread Thread-18 (webui_worker):
Traceback (most recent call last):
  File "S:\python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "S:\python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "S:\reForge\webui.py", line 69, in webui_worker
    shared.demo = ui.create_ui()
  File "S:\reForge\modules\ui.py", line 1133, in create_ui
    parameters_copypaste.connect_paste_params_buttons()
  File "S:\reForge\modules\infotext_utils.py", line 141, in connect_paste_params_buttons
    destination_image_component = paste_fields[binding.tabname]["init_img"]
KeyError: 'svd'
```

### Additional information

delete config.json ( sd_forge_svd ,) can start normally
Code: Main

**Comment by Panchovix** [comment]
Hi there, thank for the report. Nice find! Pushed a new commit that fixes this.
