### ISSUE TITLE
[Bug]: NameError: name 'comfy' is not defined

### ISSUE THREAD

**Issue by DannaRain11** [Panchovix/stable-diffusion-webui-reForge#90]
### Checklist

- [x] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

LoRAs don't seem to be working, of any type
Moved over from base Forge to reForge with the indicated guide and then swapped over to the dev branch

### Steps to reproduce the problem

1. Install reForge on a existing Forge install
2. Swap to dev branch
3. Use a lora

### What should have happened?

Lora should have loaded normally

### Sysinfo

[sysinfo-2024-07-31-04-54.json](https://github.com/user-attachments/files/16436425/sysinfo-2024-07-31-04-54.json)

### Console logs

```Shell
venv "I:\AI-Stuff\ForgeUI-SD\webui\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: f1.0.0dev-v1.10.1RC-previous-624-g12f4b8cd
Commit hash: 12f4b8cd389ab60753c4b26830fdd441e98e412e
Installing requirements
Collecting protobuf<=4.9999,>=4.25.3
  Using cached protobuf-4.25.4-cp310-abi3-win_amd64.whl (413 kB)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.0
    Uninstalling protobuf-3.20.0:
      Successfully uninstalled protobuf-3.20.0
Successfully installed protobuf-4.25.4
loading WD14-tagger reqs from I:\AI-Stuff\ForgeUI-SD\webui\extensions\stable-diffusion-webui-wd14-tagger\requirements.txt
Checking WD14-tagger requirements.
Launching Web UI with arguments: --xformers --always-gpu --disable-nan-check --cuda-malloc --cuda-stream --pin-shared-memory
Using cudaMallocAsync backend.
Total VRAM 24575 MB, total RAM 16204 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "I:\AI-Stuff\ForgeUI-SD\webui\venv\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
xformers version: 0.0.27
Set vram state to: HIGH_VRAM
Always pin shared GPU memory, disabling smart memory management
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
CUDA Stream Activated:  True
2024-07-31 01:44:22.766219: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From I:\AI-Stuff\ForgeUI-SD\webui\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

ControlNet preprocessor location: I:\AI-Stuff\ForgeUI-SD\webui\models\ControlNetPreprocessor
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 24.5.1, num models: 18
[Vec. CC] Style Sheet Loaded...
== WD14 tagger /gpu:0, uname_result(system='Windows', node='DESKTOP-283G11R', release='10', version='10.0.19045', machine='AMD64') ==
Loading model autismmixSDXL_autismmixDPO.safetensors [d3ee23d452] (1 out of 1)
Loading weights [d3ee23d452] from I:\AI-Stuff\ForgeUI-SD\webui\models\Stable-diffusion\autismmixSDXL_autismmixDPO.safetensors
[STYLE COMPONENTS]: pca loaded
I:\AI-Stuff\ForgeUI-SD\webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py:397: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  canvas_image = gr.Image(source='upload', mirror_webcam=False, type='numpy', tool='color-sketch',
I:\AI-Stuff\ForgeUI-SD\webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py:471: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  visual_regions = gr.Gallery(label="Regions").style(grid=(4, 4, 4, 8), height="auto")
I:\AI-Stuff\ForgeUI-SD\webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py:471: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'columns' in the constructor instead.
  visual_regions = gr.Gallery(label="Regions").style(grid=(4, 4, 4, 8), height="auto")
[STYLE COMPONENTS]: pca loaded
2024-07-31 01:45:02,990 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 105.5s (prepare environment: 45.4s, import torch: 12.8s, import gradio: 3.2s, setup paths: 14.2s, initialize shared: 1.3s, other imports: 3.7s, list SD models: 2.2s, load scripts: 16.9s, create ui: 4.9s, gradio launch: 0.7s).
clip missing: ['clip_l.text_projection', 'clip_l.logit_scale', 'clip_g.text_projection', 'clip_g.transformer.text_model.embeddings.position_ids']
clip unexpected: ['clip_g.transformer.text_projection.weight']
loaded straight to GPU
To load target model SDXL
Begin to load 1 model
Moving model(s) has taken 0.39 seconds
Loading VAE weights specified in settings: I:\AI-Stuff\ForgeUI-SD\webui\models\VAE\sdxl_vae.safetensors
To load target model SDXLClipModel
Begin to load 1 model
Moving model(s) has taken 0.62 seconds
Model loaded in 100.0s (load weights from disk: 2.4s, forge instantiate config: 0.3s, forge load real models: 77.2s, forge finalize: 0.6s, load VAE: 12.7s, load textual inversion embeddings: 0.8s, calculate empty prompt: 5.9s).
                                  activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x0000019B5ADC4580>]: NameError
Traceback (most recent call last):
  File "I:\AI-Stuff\ForgeUI-SD\webui\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "I:\AI-Stuff\ForgeUI-SD\webui\extensions-builtin\Lora\extra_networks_lora.py", line 45, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "I:\AI-Stuff\ForgeUI-SD\webui\extensions-builtin\Lora\networks.py", line 100, in load_networks
    current_sd.forge_objects.unet, current_sd.forge_objects.clip = load_lora_for_models(
  File "I:\AI-Stuff\ForgeUI-SD\webui\ldm_patched\modules\sd.py", line 68, in load_lora_for_models
    unet_keys = ldm_patched.modules.lora.model_lora_keys_unet(model.model) if model is not None else {}
  File "I:\AI-Stuff\ForgeUI-SD\webui\ldm_patched\modules\lora.py", line 286, in model_lora_keys_unet
    if isinstance(model, comfy.model_base.HunyuanDiT):
NameError: name 'comfy' is not defined

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x0000019B5ADC4040>]: NameError
Traceback (most recent call last):
  File "I:\AI-Stuff\ForgeUI-SD\webui\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "I:\AI-Stuff\ForgeUI-SD\webui\extensions-builtin\Lora\extra_networks_lora.py", line 45, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "I:\AI-Stuff\ForgeUI-SD\webui\extensions-builtin\Lora\networks.py", line 100, in load_networks
    current_sd.forge_objects.unet, current_sd.forge_objects.clip = load_lora_for_models(
  File "I:\AI-Stuff\ForgeUI-SD\webui\ldm_patched\modules\sd.py", line 68, in load_lora_for_models
    unet_keys = ldm_patched.modules.lora.model_lora_keys_unet(model.model) if model is not None else {}
  File "I:\AI-Stuff\ForgeUI-SD\webui\ldm_patched\modules\lora.py", line 286, in model_lora_keys_unet
    if isinstance(model, comfy.model_base.HunyuanDiT):
NameError: name 'comfy' is not defined

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x0000019B5ADC4580>]: NameError
Traceback (most recent call last):
  File "I:\AI-Stuff\ForgeUI-SD\webui\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "I:\AI-Stuff\ForgeUI-SD\webui\extensions-builtin\Lora\extra_networks_lora.py", line 45, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "I:\AI-Stuff\ForgeUI-SD\webui\extensions-builtin\Lora\networks.py", line 100, in load_networks
    current_sd.forge_objects.unet, current_sd.forge_objects.clip = load_lora_for_models(
  File "I:\AI-Stuff\ForgeUI-SD\webui\ldm_patched\modules\sd.py", line 68, in load_lora_for_models
    unet_keys = ldm_patched.modules.lora.model_lora_keys_unet(model.model) if model is not None else {}
  File "I:\AI-Stuff\ForgeUI-SD\webui\ldm_patched\modules\lora.py", line 286, in model_lora_keys_unet
    if isinstance(model, comfy.model_base.HunyuanDiT):
NameError: name 'comfy' is not defined

To load target model SDXL
Begin to load 1 model
Moving model(s) has taken 0.05 seconds
  3%|██▊                                                                                | 1/30 [00:05<02:34,  5.32s/it]
To load target model AutoencoderKL                                                      | 1/40 [00:07<05:07,  7.89s/it]
Begin to load 1 model
Moving model(s) has taken 0.04 seconds
Total progress:   2%|█▋                                                                 | 1/40 [00:10<06:37, 10.20s/it]
Refresh index: 100% (1436/1436), done.                                                  | 1/40 [00:10<05:07,  7.89s/it]
```

**Comment by scutix** [comment]
I have same error after switching to dev_upstream, but on the clean install, where I didnt had anything ( no extensions, etc.) loras are working fine on dev_upstream, I turned off extensions on the first one but still got the error
```
Traceback (most recent call last):
  File "C:\Users\xscut\OneDrive\Desktop\Stable Diffusion\Data\Packages\stable-diffusion-webui-reForge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\Users\xscut\OneDrive\Desktop\Stable Diffusion\Data\Packages\stable-diffusion-webui-reForge\extensions-builtin\Lora\extra_networks_lora.py", line 45, in activate
    networks.load_networks(names, te_multipliers, unet_multipliers, dyn_dims)
  File "C:\Users\xscut\OneDrive\Desktop\Stable Diffusion\Data\Packages\stable-diffusion-webui-reForge\extensions-builtin\Lora\networks.py", line 100, in load_networks
    current_sd.forge_objects.unet, current_sd.forge_objects.clip = load_lora_for_models(
  File "C:\Users\xscut\OneDrive\Desktop\Stable Diffusion\Data\Packages\stable-diffusion-webui-reForge\ldm_patched\modules\sd.py", line 68, in load_lora_for_models
    unet_keys = ldm_patched.modules.lora.model_lora_keys_unet(model.model) if model is not None else {}
  File "C:\Users\xscut\OneDrive\Desktop\Stable Diffusion\Data\Packages\stable-diffusion-webui-reForge\ldm_patched\modules\lora.py", line 286, in model_lora_keys_unet
    if isinstance(model, comfy.model_base.HunyuanDiT):
NameError: name 'comfy' is not defined
```

**Comment by Panchovix** [comment]
Hi there, this is now fixed since https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/92c64e49de8fbc0adce4706098df1cde1e76dd39

My bad!
